CREATE TABLE sma_products (
id INTEGER PRIMARY KEY,
id_cloud INTEGER,
code TEXT,
name TEXT,
unit INTEGER DEFAULT NULL,
cost decimal(25,4) DEFAULT NULL,
avg_cost decimal(25,4) DEFAULT NULL,
price decimal(25,4),
alert_quantity decimal(15,4) DEFAULT '20.0000',
image TEXT  DEFAULT 'no_image.png',
category_id INTEGER,
subcategory_id INTEGER DEFAULT NULL,
cf1 TEXT  DEFAULT NULL,
cf2 TEXT  DEFAULT NULL,
cf3 TEXT  DEFAULT NULL,
cf4 TEXT  DEFAULT NULL,
cf5 TEXT  DEFAULT NULL,
cf6 TEXT  DEFAULT NULL,
quantity decimal(15,4) DEFAULT '0.0000',
tax_rate INTEGER DEFAULT NULL,
track_quantity INTEGER DEFAULT '1',
details TEXT  DEFAULT NULL,
warehouse INTEGER DEFAULT NULL,
barcode_symbology TEXT  DEFAULT 'code128',
file TEXT  DEFAULT NULL,
product_details mediumtext,
tax_method INTEGER DEFAULT '0',
type TEXT  DEFAULT 'standard',
supplier1 INTEGER DEFAULT NULL,
supplier1price decimal(25,4) DEFAULT NULL,
supplier2 INTEGER DEFAULT NULL,
supplier2price decimal(25,4) DEFAULT NULL,
supplier3 INTEGER DEFAULT NULL,
supplier3price decimal(25,4) DEFAULT NULL,
supplier4 INTEGER DEFAULT NULL,
supplier4price decimal(25,4) DEFAULT NULL,
supplier5 INTEGER DEFAULT NULL,
supplier5price decimal(25,4) DEFAULT NULL,
promotion INTEGER DEFAULT '0',
promo_price decimal(25,4) DEFAULT NULL,
start_date date DEFAULT NULL,
end_date date DEFAULT NULL,
supplier1_part_no TEXT  DEFAULT NULL,
supplier2_part_no TEXT  DEFAULT NULL,
supplier3_part_no TEXT  DEFAULT NULL,
supplier4_part_no TEXT  DEFAULT NULL,
supplier5_part_no TEXT  DEFAULT NULL,
sale_unit INTEGER DEFAULT NULL,
purchase_unit INTEGER DEFAULT NULL,
brand INTEGER DEFAULT NULL,
slug TEXT  DEFAULT NULL,
featured INTEGER DEFAULT NULL,
weight decimal(10,4) DEFAULT NULL,
hsn_code INTEGER DEFAULT NULL,
views INTEGER DEFAULT '0',
hide INTEGER DEFAULT '0',
second_name TEXT  DEFAULT NULL,
reference TEXT  DEFAULT NULL,
has_multiple_units INTEGER DEFAULT NULL,
profitability_margin decimal(5,2) DEFAULT '0.00',
ignore_hide_parameters INTEGER DEFAULT '0',
consumption_sale_tax INTEGER DEFAULT '0',
consumption_purchase_tax INTEGER DEFAULT '0',
discontinued INTEGER DEFAULT '0',
attributes INTEGER DEFAULT '0',
supplier1price_date datetime DEFAULT NULL,
supplier2price_date datetime DEFAULT NULL,
supplier3price_date datetime DEFAULT NULL,
supplier4price_date datetime DEFAULT NULL,
supplier5price_date datetime DEFAULT NULL,
registration_date timestamp DEFAULT CURRENT_TIMESTAMP,
last_update datetime DEFAULT CURRENT_TIMESTAMP
);


  CREATE TABLE sma_product_variants (
id INTEGER PRIMARY KEY,
product_id INTEGER,
name TEXT,
cost decimal(25,4) DEFAULT NULL,
price decimal(25,4) DEFAULT NULL,
quantity decimal(15,4) DEFAULT NULL,
suffix TEXT  DEFAULT NULL,
color TEXT  DEFAULT NULL,
last_update datetime DEFAULT CURRENT_TIMESTAMP
);


  CREATE TABLE sma_product_prices (
id INTEGER PRIMARY KEY,
id_cloud INTEGER,
product_id INTEGER,
price_group_id INTEGER,
price decimal(25,4),
last_update datetime DEFAULT CURRENT_TIMESTAMP
);


  CREATE TABLE sma_price_groups (
id INTEGER PRIMARY KEY,
id_cloud INTEGER,
name TEXT,
price_group_base INTEGER DEFAULT '0',
last_update datetime DEFAULT CURRENT_TIMESTAMP
);



CREATE TABLE sma_product_photos (
id INTEGER PRIMARY KEY,
id_cloud INTEGER,
product_id INTEGER,
photo TEXT,
last_update datetime DEFAULT CURRENT_TIMESTAMP
);


  CREATE TABLE sma_companies (
id INTEGER PRIMARY KEY,
id_cloud INTEGER,
group_id INTEGER  DEFAULT NULL,
group_name TEXT,
customer_group_id INTEGER DEFAULT NULL,
customer_group_name TEXT  DEFAULT NULL,
type_person INTEGER DEFAULT NULL,
name TEXT,
first_name TEXT,
second_name TEXT,
first_lastname TEXT,
second_lastname TEXT,
company TEXT,
commercial_register TEXT,
tipo_documento INTEGER DEFAULT NULL,
document_code INTEGER,
vat_no TEXT  DEFAULT NULL,
digito_verificacion INTEGER DEFAULT NULL,
address TEXT  DEFAULT NULL,
location TEXT,
subzone TEXT  DEFAULT NULL,
city TEXT  DEFAULT NULL,
state TEXT  DEFAULT NULL,
postal_code TEXT  DEFAULT NULL,
country TEXT  DEFAULT NULL,
phone TEXT  DEFAULT NULL,
email TEXT,
cf1 TEXT  DEFAULT NULL,
cf2 TEXT  DEFAULT NULL,
cf3 TEXT  DEFAULT NULL,
cf4 TEXT  DEFAULT NULL,
cf5 TEXT  DEFAULT NULL,
cf6 TEXT  DEFAULT NULL,
invoice_footer text,
payment_term INTEGER DEFAULT '0',
logo TEXT  DEFAULT 'logo.png',
award_points INTEGER DEFAULT '0',
deposit_amount decimal(25,4) DEFAULT NULL,
price_group_id INTEGER DEFAULT NULL,
price_group_name TEXT  DEFAULT NULL,
id_partner TEXT  DEFAULT NULL,
tipo_regimen INTEGER DEFAULT NULL,
city_code TEXT,
status INTEGER DEFAULT '1',
birth_month INTEGER DEFAULT '0',
birth_day INTEGER DEFAULT '0',
customer_only_for_pos INTEGER DEFAULT NULL,
customer_seller_id_assigned INTEGER DEFAULT NULL,
customer_special_discount INTEGER DEFAULT '0',
fuente_retainer INTEGER DEFAULT '0',
iva_retainer INTEGER DEFAULT '0',
ica_retainer INTEGER DEFAULT '0',
default_rete_fuente_id INTEGER DEFAULT NULL,
default_rete_iva_id INTEGER DEFAULT NULL,
default_rete_ica_id INTEGER DEFAULT NULL,
default_rete_other_id INTEGER DEFAULT NULL,
customer_payment_type INTEGER DEFAULT '0',
customer_credit_limit decimal(25,4) DEFAULT '0.0000',
customer_payment_term INTEGER DEFAULT '0',
customer_validate_min_base_retention INTEGER DEFAULT '0',
gender INTEGER DEFAULT NULL,
logo_square TEXT  DEFAULT 'logo.png',
tax_exempt_customer INTEGER DEFAULT '0',
initial_accounting_balance_transferred INTEGER DEFAULT '0',
customer_profile_photo TEXT  DEFAULT NULL,
supplier_type INTEGER DEFAULT '1',
note TEXT  DEFAULT NULL,
last_update datetime DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE sma_biller_data (
id INTEGER PRIMARY KEY,
id_cloud INTEGER,
biller_id INTEGER,
pos_document_type_default INTEGER DEFAULT NULL,
detal_document_type_default INTEGER DEFAULT NULL,
default_price_group INTEGER DEFAULT NULL,
default_warehouse_id INTEGER DEFAULT NULL,
default_customer_id INTEGER DEFAULT NULL,
default_seller_id INTEGER DEFAULT NULL,
key_log INTEGER DEFAULT '1',
product_order INTEGER DEFAULT '0',
purchases_document_type_default INTEGER DEFAULT NULL,
pin_code TEXT  DEFAULT NULL,
branch_type INTEGER DEFAULT '1',
coverage_country TEXT  DEFAULT NULL,
coverage_state TEXT  DEFAULT NULL,
coverage_city TEXT  DEFAULT NULL,
coverage_zone TEXT  DEFAULT NULL,
prioridad_precios_producto INTEGER DEFAULT NULL,
language TEXT  DEFAULT NULL,
currency TEXT  DEFAULT NULL,
charge_shipping_cost INTEGER DEFAULT NULL,
shipping_cost decimal(25,4) DEFAULT NULL,
max_total_shipping_cost decimal(25,4) DEFAULT NULL,
concession_status INTEGER DEFAULT '0',
default_pos_section INTEGER DEFAULT NULL,
preparation_adjustment_document_type_id INTEGER DEFAULT NULL,
default_cost_center_id INTEGER DEFAULT NULL,
rete_bomberil_percentage decimal(6,3) DEFAULT '0.000',
rete_bomberil_account INTEGER DEFAULT '0',
rete_bomberil_account_counterpart INTEGER DEFAULT '0',
rete_autoaviso_percentage decimal(6,3) DEFAULT '0.000',
rete_autoaviso_account INTEGER DEFAULT '0',
rete_autoaviso_account_counterpart INTEGER DEFAULT '0',
rete_autoica_percentage decimal(6,3) DEFAULT '0.000',
rete_autoica_account INTEGER DEFAULT '0',
rete_autoica_account_counterpart INTEGER DEFAULT '0',
cash_payment_method_account INTEGER DEFAULT NULL,
pin_code_request INTEGER DEFAULT '3',
pin_code_method INTEGER DEFAULT '1',
random_pin_code TEXT  DEFAULT '98987878747471424454745',
random_pin_code_date datetime DEFAULT NULL,
last_update datetime DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE sma_customer_groups (
id INTEGER PRIMARY KEY,
id_cloud INTEGER,
name TEXT,
percent INTEGER,
last_update datetime DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE sma_settings (
setting_id INTEGER,
logo TEXT,
logo2 TEXT,
site_name TEXT,
language TEXT,
default_warehouse INTEGER,
accounting_method INTEGER DEFAULT '0',
default_currency TEXT,
default_tax_rate INTEGER,
rows_per_page INTEGER,
version TEXT  DEFAULT '1.0',
default_tax_rate2 INTEGER DEFAULT '0',
dateformat INTEGER,
sales_prefix TEXT  DEFAULT NULL,
quote_prefix TEXT  DEFAULT NULL,
quote_purchase_prefix TEXT  DEFAULT NULL,
order_sale_prefix TEXT  DEFAULT NULL,
purchase_prefix TEXT  DEFAULT NULL,
transfer_prefix TEXT  DEFAULT NULL,
delivery_prefix TEXT  DEFAULT NULL,
payment_prefix TEXT  DEFAULT NULL,
return_prefix TEXT  DEFAULT NULL,
returnp_prefix TEXT  DEFAULT NULL,
expense_prefix TEXT  DEFAULT NULL,
item_addition INTEGER DEFAULT '0',
theme TEXT,
product_serial INTEGER,
default_discount INTEGER,
product_discount INTEGER DEFAULT '0',
discount_method INTEGER,
tax1 INTEGER,
tax2 INTEGER,
tax3 INTEGER,
overselling INTEGER DEFAULT '0',
restrict_user INTEGER DEFAULT '0',
restrict_calendar INTEGER DEFAULT '0',
timezone TEXT  DEFAULT NULL,
iwidth INTEGER DEFAULT '0',
iheight INTEGER,
twidth INTEGER,
theight INTEGER,
watermark INTEGER DEFAULT NULL,
reg_ver INTEGER DEFAULT NULL,
allow_reg INTEGER DEFAULT NULL,
reg_notification INTEGER DEFAULT NULL,
auto_reg INTEGER DEFAULT NULL,
protocol TEXT  DEFAULT 'mail',
mailpath TEXT  DEFAULT '/usr/sbin/sendmail',
smtp_host TEXT  DEFAULT NULL,
smtp_user TEXT  DEFAULT NULL,
smtp_pass TEXT  DEFAULT NULL,
smtp_port TEXT  DEFAULT '25',
smtp_crypto TEXT  DEFAULT NULL,
corn datetime DEFAULT NULL,
customer_group INTEGER,
default_email TEXT,
mmode INTEGER,
bc_fix INTEGER DEFAULT '0',
auto_detect_barcode INTEGER DEFAULT '0',
captcha INTEGER DEFAULT '1',
reference_format INTEGER DEFAULT '1',
racks INTEGER DEFAULT '0',
attributes INTEGER DEFAULT '0',
product_expiry INTEGER DEFAULT '0',
decimals INTEGER DEFAULT '2',
qty_decimals INTEGER DEFAULT '2',
decimals_sep TEXT  DEFAULT '.',
thousands_sep TEXT  DEFAULT ',',
invoice_view INTEGER DEFAULT '0',
default_biller INTEGER DEFAULT NULL,
envato_username TEXT  DEFAULT NULL,
purchase_code TEXT  DEFAULT NULL,
rtl INTEGER DEFAULT '0',
each_spent decimal(15,4) DEFAULT NULL,
ca_point INTEGER DEFAULT NULL,
each_sale decimal(15,4) DEFAULT NULL,
sa_point INTEGER DEFAULT NULL,
updates INTEGER DEFAULT '0',
sac INTEGER DEFAULT '0',
display_all_products INTEGER DEFAULT '0',
display_symbol INTEGER DEFAULT NULL,
symbol TEXT  DEFAULT NULL,
remove_expired INTEGER DEFAULT '0',
barcode_separator TEXT  DEFAULT '_',
set_focus INTEGER DEFAULT '0',
price_group INTEGER DEFAULT NULL,
barcode_img INTEGER DEFAULT '1',
ppayment_prefix TEXT  DEFAULT 'POP',
disable_editing INTEGER DEFAULT '90',
qa_prefix TEXT  DEFAULT NULL,
update_cost INTEGER DEFAULT NULL,
apis INTEGER DEFAULT '0',
pdf_lib TEXT  DEFAULT NULL,
state TEXT  DEFAULT NULL,
sma_payment_prefix TEXT  DEFAULT NULL,
deposit_prefix TEXT  DEFAULT NULL,
cashier_close INTEGER DEFAULT '0',
alert_sale_expired INTEGER DEFAULT '0',
tipo_regimen INTEGER DEFAULT '1',
purchase_tax_rate INTEGER DEFAULT '1',
modulary INTEGER DEFAULT '0',
resolucion_porc_aviso decimal(4,2) DEFAULT '0.00',
resolucion_dias_aviso INTEGER DEFAULT '0',
prioridad_precios_producto INTEGER DEFAULT '1',
descuento_orden INTEGER DEFAULT '1',
allow_change_sale_iva INTEGER DEFAULT '0',
tax_rate_traslate INTEGER DEFAULT '0',
get_companies_check_digit INTEGER DEFAULT '1',
tipo_persona INTEGER,
tipo_documento TEXT,
digito_verificacion INTEGER DEFAULT NULL,
numero_documento TEXT,
razon_social TEXT,
nombre_comercial TEXT,
primer_nombre TEXT,
segundo_nombre TEXT,
primer_apellido TEXT,
segundo_apellido TEXT,
matricula_mercantil TEXT,
direccion TEXT,
localidad TEXT,
postal_code TEXT,
ciudad TEXT,
city_code TEXT  DEFAULT NULL,
departamento TEXT,
pais TEXT,
allow_advanced_search INTEGER DEFAULT '0',
rounding INTEGER DEFAULT '0',
purchase_payment_affects_cash_register INTEGER DEFAULT '2',
digital_signature TEXT,
max_num_results_display INTEGER DEFAULT '15',
cost_center_selection INTEGER DEFAULT '2',
hide_products_in_zero_price INTEGER DEFAULT '0',
default_cost_center INTEGER DEFAULT NULL,
tax_rate_translate INTEGER DEFAULT '0',
electronic_billing INTEGER DEFAULT '0',
fe_technology_provider INTEGER DEFAULT NULL,
fe_user TEXT  DEFAULT NULL,
fe_password TEXT  DEFAULT NULL,
tax_method INTEGER DEFAULT '2',
show_alert_sale_expired INTEGER DEFAULT '1',
customer_default_country TEXT  DEFAULT NULL,
customer_default_state TEXT  DEFAULT NULL,
customer_default_city TEXT  DEFAULT NULL,
set_adjustment_cost INTEGER DEFAULT '0',
default_records_filter INTEGER DEFAULT '0',
show_brand_in_product_search INTEGER DEFAULT '0',
close_year_step INTEGER DEFAULT '0',
closed_from_another_year INTEGER DEFAULT '0',
precios_por_unidad_presentacion INTEGER DEFAULT NULL,
lock_cost_field_in_product INTEGER DEFAULT '1',
fuente_retainer INTEGER DEFAULT '0',
iva_retainer INTEGER DEFAULT '0',
ica_retainer INTEGER DEFAULT '0',
export_to_csv_each_new_customer INTEGER DEFAULT '0',
commision_payment_method INTEGER DEFAULT '1',
default_expense_id_to_pay_commisions INTEGER DEFAULT NULL,
margin_price_formula INTEGER DEFAULT '0',
users_can_view_price_groups INTEGER DEFAULT '0',
users_can_view_warehouse_quantitys INTEGER DEFAULT '0',
product_variant_language TEXT  DEFAULT NULL,
product_variants_language TEXT  DEFAULT NULL,
send_electronic_invoice_to INTEGER DEFAULT '1',
copy_mail_to_sender INTEGER DEFAULT '0',
days_before_current_date INTEGER DEFAULT '0',
days_after_current_date INTEGER DEFAULT '0',
add_individual_attachments INTEGER DEFAULT '0',
product_crud_validate_cost INTEGER DEFAULT NULL,
alert_zero_cost_sale INTEGER DEFAULT NULL,
customer_branch_language TEXT  DEFAULT NULL,
customer_branches_language TEXT  DEFAULT NULL,
barcode_reader_exact_search INTEGER DEFAULT '0',
which_cost_margin_validation INTEGER DEFAULT '1',
max_minutes_random_pin_code INTEGER DEFAULT '5',
cron_job_db_backup INTEGER DEFAULT '1',
cron_job_images_backup INTEGER DEFAULT '1',
cron_job_ebilling_backup INTEGER DEFAULT '1',
cron_job_send_mail INTEGER DEFAULT '1',
fe_work_environment INTEGER DEFAULT '1',
fe_technical_annex_version INTEGER DEFAULT '1',
management_consecutive_suppliers INTEGER DEFAULT '0',
url_web TEXT  DEFAULT NULL,
profitability_margin_validation INTEGER DEFAULT NULL,
prorate_shipping_cost INTEGER DEFAULT '0',
session_expiration_time INTEGER DEFAULT '15',
product_order INTEGER DEFAULT '1',
keep_seller_from_user INTEGER DEFAULT '0',
invoice_values_greater_than_zero INTEGER DEFAULT '1',
except_category_taxes INTEGER DEFAULT '0',
category_tax_exception_start_date date DEFAULT NULL,
category_tax_exception_end_date date DEFAULT NULL,
category_tax_exception_tax_rate_id INTEGER DEFAULT NULL,
customer_territorial_decree_tax_rate_id INTEGER DEFAULT NULL,
ipoconsumo INTEGER DEFAULT NULL,
default_return_payment_method TEXT  DEFAULT '0',
manual_payment_reference INTEGER DEFAULT '0',
self_withholding_percentage decimal(25,4) DEFAULT '0.0000',
item_discount_apply_to INTEGER DEFAULT '2',
gift_card_language TEXT  DEFAULT NULL,
automatic_update INTEGER DEFAULT '0',
wappsi_rest_url mediumtext,
dropbox_key mediumtext 
dropbox_secret mediumtext 
dropbox_token mediumtext 
detail_due_sales INTEGER DEFAULT '0',
detail_partial_sales INTEGER DEFAULT '0',
detail_paid_sales INTEGER DEFAULT '0',
detail_products_expirated INTEGER DEFAULT '0',
detail_products_promo_expirated INTEGER DEFAULT '0',
detail_sales_per_biller INTEGER DEFAULT '0',
detail_pos_registers INTEGER DEFAULT '0',
detail_zeta_report INTEGER DEFAULT '0',
great_contributor INTEGER DEFAULT '0',
annual_closure INTEGER DEFAULT '0',
product_variant_per_serial INTEGER DEFAULT '0',
product_search_show_quantity INTEGER DEFAULT '1',
suspended_sales_to_retail INTEGER DEFAULT '1',
payments_methods_retcom INTEGER DEFAULT '0',
product_default_exempt_tax_rate INTEGER,
ciiu_code_id INTEGER DEFAULT NULL,
production_order_one_reference_limit INTEGER DEFAULT NULL,
system_start_date date DEFAULT '2018-01-01',
set_product_variant_suffix INTEGER DEFAULT '0',
disable_product_price_under_cost INTEGER DEFAULT '1',
wms_picking_filter_biller INTEGER DEFAULT '0',
accounting_year_suffix TEXT  DEFAULT NULL,
enable_customer_tax_exemption INTEGER DEFAULT '1',
block_movements_from_another_year INTEGER DEFAULT '0',
product_transformation_validate_quantity INTEGER DEFAULT '1',
rete_other_language TEXT  DEFAULT NULL,
last_update datetime DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (setting_id)
);

CREATE TABLE sma_addresses (
id INTEGER DEFAULT 1,
id_cloud INTEGER,
company_id INTEGER,
direccion TEXT,
sucursal TEXT  DEFAULT NULL,
city TEXT,
postal_code TEXT  DEFAULT NULL,
state TEXT,
country TEXT,
phone TEXT  DEFAULT NULL,
updated_at timestamp,
city_code TEXT  DEFAULT NULL,
customer_address_seller_id_assigned INTEGER DEFAULT NULL,
customer_group_id INTEGER DEFAULT NULL,
customer_group_name TEXT  DEFAULT NULL,
price_group_id INTEGER DEFAULT NULL,
price_group_name TEXT  DEFAULT NULL,
seller_sale_comision decimal(25,4) DEFAULT '0.0000',
seller_collection_comision decimal(25,4) DEFAULT '0.0000',
code TEXT  DEFAULT NULL,
line1 TEXT  DEFAULT NULL,
line2 TEXT  DEFAULT NULL,
email TEXT  DEFAULT NULL,
vat_no TEXT  DEFAULT NULL,
last_update datetime DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE sync (
id INTEGER,
last_update datetime DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE sma_warehouses_products (
id INTEGER PRIMARY KEY,
product_id INTEGER NOT NULL,
warehouse_id INTEGER NOT NULL,
quantity decimal(15,4) NOT NULL,
rack TEXT  DEFAULT NULL,
avg_cost decimal(25,4) NOT NULL,
closed_year INTEGER DEFAULT '0' ,
warehouse_location TEXT  DEFAULT NULL
);

CREATE TABLE sma_brands (
id INTEGER PRIMARY KEY,
code TEXT  DEFAULT NULL,
name TEXT  NOT NULL,
image TEXT  DEFAULT NULL,
slug TEXT  DEFAULT NULL
);

CREATE TABLE sma_payment_methods (
id INTEGER NOT NULL PRIMARY KEY,
name TEXT  NOT NULL,
code TEXT  NOT NULL,
state_sale INTEGER NOT NULL DEFAULT '1' ,
state_purchase INTEGER NOT NULL DEFAULT '1' ,
code_fe TEXT  NOT NULL ,
cash_payment INTEGER DEFAULT '0' ,
due_payment INTEGER NOT NULL DEFAULT '0' ,
commision_value TEXT  DEFAULT NULL,
commision_ledger_id INTEGER DEFAULT NULL,
retefuente_value TEXT  DEFAULT NULL,
retefuente_ledger_id INTEGER DEFAULT NULL,
reteiva_value TEXT  DEFAULT NULL,
reteiva_ledger_id INTEGER DEFAULT NULL,
reteica_value TEXT  DEFAULT NULL,
reteica_ledger_id INTEGER DEFAULT NULL,
supplier_id INTEGER DEFAULT NULL,
icon TEXT  DEFAULT 'default.png',
biller_accountant_parametrization INTEGER DEFAULT '0' ,
billers text 
);


CREATE UNIQUE INDEX sma_products_code ON sma_products (code);
CREATE INDEX sma_products_category_id ON sma_products (category_id);
CREATE INDEX sma_products_id ON sma_products (id);
CREATE INDEX sma_products_id_2 ON sma_products (id);
CREATE INDEX sma_products_category_id_2 ON sma_products (category_id);
CREATE INDEX sma_products_unit ON sma_products (unit);
CREATE INDEX sma_products_brand ON sma_products (brand);
CREATE INDEX sma_product_prices_product_id ON sma_product_prices (product_id);
CREATE INDEX sma_product_prices_price_group_id ON sma_product_prices (price_group_id);
CREATE INDEX sma_price_groups_name ON sma_price_groups (name);
CREATE INDEX sma_companies_group_id ON sma_companies (group_id);
CREATE INDEX sma_addresses_company_id ON sma_addresses (company_id);
CREATE INDEX sma_companies_group_id_2 ON sma_companies (group_id);
CREATE INDEX sma_warehouses_products_product_id ON sma_warehouses_products (product_id);
CREATE INDEX sma_warehouses_products_warehouse_id ON sma_warehouses_products (warehouse_id);
CREATE INDEX sma_brands_name ON sma_brands (name);



PRAGMA ignore_check_constraints = ON;
PRAGMA foreign_keys = ON;
PRAGMA journal_mode = WAL;
PRAGMA synchronous = NORMAL;


INSERT INTO sync (id,last_update) VALUES (1,'1998-08-28 09:23:45');
INSERT INTO sync (id, last_update) VALUES (2,'1998-08-28 09:23:45');
INSERT INTO sync (id,last_update) VALUES (3,'1998-08-28 09:23:45');
INSERT INTO sync (id,last_update) VALUES (4,'1998-08-28 09:23:45');
INSERT INTO sync (id,last_update) VALUES (5,'1998-08-28 09:23:45');
INSERT INTO sync (id,last_update) VALUES (6,'1998-08-28 09:23:45');
INSERT INTO sync (id,last_update) VALUES (7,'1998-08-28 09:23:45');
INSERT INTO sync (id,last_update) VALUES (8,'1998-08-28 09:23:45');
INSERT INTO sync (id,last_update) VALUES (9,'1998-08-28 09:23:45');
INSERT INTO sync (id,last_update) VALUES (10,'1998-08-28 09:23:45');
INSERT INTO sync (id,last_update) VALUES (11,'1998-08-28 09:23:45');