//______________________________________________________________________________________________________________
//
//                                              DB CREATION
//_______________________________________________________________________________________________________________

// ignore_for_file: constant_identifier_names

const String DbProductsSql = '''
  CREATE TABLE sma_products (
id INTEGER PRIMARY KEY,
id_cloud INTEGER,
code TEXT,
name TEXT,
unit INTEGER DEFAULT NULL,
cost decimal(25,4) DEFAULT NULL,
avg_cost decimal(25,4) DEFAULT NULL,
price decimal(25,4),
alert_quantity decimal(15,4) DEFAULT '20.0000',
image TEXT  DEFAULT 'no_image.png',
category_id INTEGER,
subcategory_id INTEGER DEFAULT NULL,
cf1 TEXT  DEFAULT NULL,
cf2 TEXT  DEFAULT NULL,
cf3 TEXT  DEFAULT NULL,
cf4 TEXT  DEFAULT NULL,
cf5 TEXT  DEFAULT NULL,
cf6 TEXT  DEFAULT NULL,
quantity decimal(15,4) DEFAULT '0.0000',
tax_rate INTEGER DEFAULT NULL,
track_quantity INTEGER DEFAULT '1',
details TEXT  DEFAULT NULL,
warehouse INTEGER DEFAULT NULL,
barcode_symbology TEXT  DEFAULT 'code128',
file TEXT  DEFAULT NULL,
product_details TEXT,
tax_method INTEGER DEFAULT '0',
type TEXT  DEFAULT 'standard',
supplier1 INTEGER DEFAULT NULL,
supplier1price decimal(25,4) DEFAULT NULL,
supplier2 INTEGER DEFAULT NULL,
supplier2price decimal(25,4) DEFAULT NULL,
supplier3 INTEGER DEFAULT NULL,
supplier3price decimal(25,4) DEFAULT NULL,
supplier4 INTEGER DEFAULT NULL,
supplier4price decimal(25,4) DEFAULT NULL,
supplier5 INTEGER DEFAULT NULL,
supplier5price decimal(25,4) DEFAULT NULL,
promotion INTEGER DEFAULT '0',
promo_price decimal(25,4) DEFAULT NULL,
start_date date DEFAULT NULL,
end_date date DEFAULT NULL,
supplier1_part_no TEXT  DEFAULT NULL,
supplier2_part_no TEXT  DEFAULT NULL,
supplier3_part_no TEXT  DEFAULT NULL,
supplier4_part_no TEXT  DEFAULT NULL,
supplier5_part_no TEXT  DEFAULT NULL,
sale_unit INTEGER DEFAULT NULL,
purchase_unit INTEGER DEFAULT NULL,
brand INTEGER DEFAULT NULL,
slug TEXT  DEFAULT NULL,
featured INTEGER DEFAULT NULL,
weight decimal(10,4) DEFAULT NULL,
hsn_code INTEGER DEFAULT NULL,
views INTEGER DEFAULT '0',
hide_detal INTEGER DEFAULT '0',
hide_pos INTEGER DEFAULT '0',
hide_online_store INTEGER DEFAULT '0',
second_name TEXT  DEFAULT NULL,
reference TEXT  DEFAULT NULL,
has_multiple_units INTEGER DEFAULT NULL,
profitability_margin decimal(5,2) DEFAULT '0.00',
ignore_hide_parameters INTEGER DEFAULT '0',
consumption_sale_tax INTEGER DEFAULT '0',
consumption_purchase_tax INTEGER DEFAULT '0',
discontinued INTEGER DEFAULT '0',
attributes INTEGER DEFAULT '0',
supplier1price_date datetime DEFAULT NULL,
supplier2price_date datetime DEFAULT NULL,
supplier3price_date datetime DEFAULT NULL,
supplier4price_date datetime DEFAULT NULL,
supplier5price_date datetime DEFAULT NULL,
registration_date timestamp DEFAULT CURRENT_TIMESTAMP,
last_update datetime DEFAULT CURRENT_TIMESTAMP
);
''';

const String DbProductVariantsSql = '''
  CREATE TABLE sma_product_variants (
id INTEGER PRIMARY KEY,
id_cloud INTEGER,
product_id INTEGER,
name TEXT,
cost decimal(25,4) DEFAULT NULL,
price decimal(25,4) DEFAULT NULL,
quantity decimal(15,4) DEFAULT NULL,
suffix TEXT  DEFAULT NULL,
color TEXT  DEFAULT NULL,
last_update datetime DEFAULT CURRENT_TIMESTAMP
);
''';

const String DbProductsPriceSql = '''
  CREATE TABLE sma_product_prices (
id INTEGER PRIMARY KEY,
id_cloud INTEGER,
product_id INTEGER,
price_group_id INTEGER,
price decimal(25,4),
last_update datetime DEFAULT CURRENT_TIMESTAMP
);
''';

// to manage product preferences

const String DbProductPreferencesSql = '''
CREATE TABLE `sma_product_preferences` (
`id` INTEGER NOT NULL PRIMARY KEY,
`id_cloud` INTEGER NOT NULL,
`product_id` INTEGER NOT NULL,
`name` TEXT  DEFAULT NULL,
`preference_id` INTEGER DEFAULT NULL,
`preference_category_id` INTEGER DEFAULT NULL
);
''';

const String DbPreferencesSql = '''
CREATE TABLE `sma_preferences` (
`id` INTEGER NOT NULL PRIMARY KEY,
`category_id` INTEGER NOT NULL,
`name` TEXT  DEFAULT NULL
);
''';

const String DbPreferencesCategoriresSql = '''
CREATE TABLE `sma_preferences_categories` (
`id` INTEGER NOT NULL PRIMARY KEY,
`name` TEXT  DEFAULT NULL,
`selection_limit` INTEGER DEFAULT '0',
`required` INTEGER DEFAULT '0'
);
''';

const String DbPriceGroupsSql = '''
  CREATE TABLE sma_price_groups (
id INTEGER PRIMARY KEY,
id_cloud INTEGER,
name TEXT,
price_group_base INTEGER DEFAULT '0',
last_update datetime DEFAULT CURRENT_TIMESTAMP
);

''';

const String DbTaxRatesSql = '''
CREATE TABLE `sma_tax_rates` (
id_cloud INTEGER NOT NULL,
id INTEGER PRIMARY KEY,
name TEXT  NOT NULL,
code TEXT  DEFAULT NULL,
rate decimal(12,4) NOT NULL,
type TEXT  NOT NULL,
tax_class INTEGER NOT NULL DEFAULT '1' ,
code_fe TEXT  NOT NULL ,
tax_indicator TEXT  DEFAULT NULL,
last_update datetime NOT NULL DEFAULT CURRENT_TIMESTAMP
);

''';

const String DbProductPhotosSql = '''
CREATE TABLE sma_product_photos (
id INTEGER PRIMARY KEY,
id_cloud INTEGER,
product_id INTEGER,
photo TEXT,
last_update datetime DEFAULT CURRENT_TIMESTAMP
);
''';

const String DbCompaniesSql = '''
  CREATE TABLE sma_companies (
id INTEGER PRIMARY KEY,
id_cloud INTEGER,
group_id INTEGER  DEFAULT NULL,
group_name TEXT,
customer_group_id INTEGER DEFAULT NULL,
customer_group_name TEXT  DEFAULT NULL,
type_person INTEGER DEFAULT NULL,
name TEXT,
first_name TEXT,
second_name TEXT,
first_lastname TEXT,
second_lastname TEXT,
company TEXT,
commercial_register TEXT,
tipo_documento INTEGER DEFAULT NULL,
document_code INTEGER,
vat_no TEXT  DEFAULT NULL,
digito_verificacion INTEGER DEFAULT NULL,
address TEXT  DEFAULT NULL,
location TEXT,
subzone TEXT  DEFAULT NULL,
city TEXT  DEFAULT NULL,
state TEXT  DEFAULT NULL,
postal_code TEXT  DEFAULT NULL,
country TEXT  DEFAULT NULL,
phone TEXT  DEFAULT NULL,
email TEXT,
cf1 TEXT  DEFAULT NULL,
cf2 TEXT  DEFAULT NULL,
cf3 TEXT  DEFAULT NULL,
cf4 TEXT  DEFAULT NULL,
cf5 TEXT  DEFAULT NULL,
cf6 TEXT  DEFAULT NULL,
invoice_footer TEXT, 
payment_term INTEGER DEFAULT '0',
logo TEXT  DEFAULT 'logo.png',
award_points INTEGER DEFAULT '0',
deposit_amount decimal(25,4) DEFAULT NULL,
price_group_id INTEGER DEFAULT NULL,
price_group_name TEXT  DEFAULT NULL,
id_partner TEXT  DEFAULT NULL,
tipo_regimen INTEGER DEFAULT NULL,
city_code TEXT,
status INTEGER DEFAULT '1',
birth_month INTEGER DEFAULT '0',
birth_day INTEGER DEFAULT '0',
customer_only_for_pos INTEGER DEFAULT NULL,
customer_seller_id_assigned INTEGER DEFAULT NULL,
customer_special_discount INTEGER DEFAULT '0',
fuente_retainer INTEGER DEFAULT '0',
iva_retainer INTEGER DEFAULT '0',

ica_retainer INTEGER DEFAULT '0',
default_rete_fuente_id INTEGER DEFAULT NULL,
default_rete_iva_id INTEGER DEFAULT NULL,
default_rete_ica_id INTEGER DEFAULT NULL,
default_rete_other_id INTEGER DEFAULT NULL,
customer_payment_type INTEGER DEFAULT '0',
customer_credit_limit decimal(25,4) DEFAULT '0.0000',
customer_payment_term INTEGER DEFAULT '0',
customer_validate_min_base_retention INTEGER DEFAULT '0',
gender INTEGER DEFAULT NULL,
logo_square TEXT  DEFAULT 'logo.png',
tax_exempt_customer INTEGER DEFAULT '0',
initial_accounting_balance_transferred INTEGER DEFAULT '0',
customer_profile_photo TEXT  DEFAULT NULL,
supplier_type INTEGER DEFAULT '1',
note TEXT  DEFAULT NULL,
last_update datetime DEFAULT CURRENT_TIMESTAMP
);
''';

const String DbBillerDataSql = '''
  CREATE TABLE sma_biller_data (
id INTEGER PRIMARY KEY,
id_cloud INTEGER,
biller_id INTEGER,
pos_document_type_default INTEGER DEFAULT NULL,
detal_document_type_default INTEGER DEFAULT NULL,
default_price_group INTEGER DEFAULT NULL,
default_warehouse_id INTEGER DEFAULT NULL,
default_customer_id INTEGER DEFAULT NULL,
default_seller_id INTEGER DEFAULT NULL,
key_log INTEGER DEFAULT '1',
product_order INTEGER DEFAULT '0',
purchases_document_type_default INTEGER DEFAULT NULL,
pin_code TEXT  DEFAULT NULL,
branch_type INTEGER DEFAULT '1',
coverage_country TEXT  DEFAULT NULL,
coverage_state TEXT  DEFAULT NULL,
coverage_city TEXT  DEFAULT NULL,
coverage_zone TEXT  DEFAULT NULL,
prioridad_precios_producto INTEGER DEFAULT NULL,
language TEXT  DEFAULT NULL,
currency TEXT  DEFAULT NULL,
charge_shipping_cost INTEGER DEFAULT NULL,
shipping_cost decimal(25,4) DEFAULT NULL,
max_total_shipping_cost decimal(25,4) DEFAULT NULL,
concession_status INTEGER DEFAULT '0',
default_pos_section INTEGER DEFAULT NULL,
preparation_adjustment_document_type_id INTEGER DEFAULT NULL,
default_cost_center_id INTEGER DEFAULT NULL,
rete_bomberil_percentage decimal(6,3) DEFAULT '0.000',
rete_bomberil_account INTEGER DEFAULT '0',
rete_bomberil_account_counterpart INTEGER DEFAULT '0',
rete_autoaviso_percentage decimal(6,3) DEFAULT '0.000',
rete_autoaviso_account INTEGER DEFAULT '0',
rete_autoaviso_account_counterpart INTEGER DEFAULT '0',
rete_autoica_percentage decimal(6,3) DEFAULT '0.000',
rete_autoica_account INTEGER DEFAULT '0',
rete_autoica_account_counterpart INTEGER DEFAULT '0',
cash_payment_method_account INTEGER DEFAULT NULL,
pin_code_request INTEGER DEFAULT '3',
pin_code_method INTEGER DEFAULT '1',
random_pin_code TEXT  DEFAULT '98987878747471424454745',
random_pin_code_date datetime DEFAULT NULL,
last_update datetime DEFAULT CURRENT_TIMESTAMP,
order_sales_document_type_default INTEGER DEFAULT NULL,
min_sale_amount decimal(25,4) DEFAULT NULL
);
''';

const String DbCustomerGroupsSql = '''
  CREATE TABLE sma_customer_groups (
id INTEGER PRIMARY KEY,
id_cloud INTEGER,
name TEXT,
percent INTEGER,
last_update datetime DEFAULT CURRENT_TIMESTAMP
);

''';

const String DbSettingsSql = '''
CREATE TABLE sma_settings (
id INTEGER PRIMARY KEY,
setting_id INTEGER,
logo TEXT,
logo2 TEXT,
site_name TEXT,
language TEXT,
default_warehouse INTEGER,
accounting_method INTEGER DEFAULT '0',
default_currency TEXT,
default_tax_rate INTEGER,
rows_per_page INTEGER,
version TEXT  DEFAULT '1.0',
default_tax_rate2 INTEGER DEFAULT '0',
dateformat INTEGER,
sales_prefix TEXT  DEFAULT NULL,
quote_prefix TEXT  DEFAULT NULL,
quote_purchase_prefix TEXT  DEFAULT NULL,
order_sale_prefix TEXT  DEFAULT NULL,
purchase_prefix TEXT  DEFAULT NULL,
transfer_prefix TEXT  DEFAULT NULL,
delivery_prefix TEXT  DEFAULT NULL,
payment_prefix TEXT  DEFAULT NULL,
return_prefix TEXT  DEFAULT NULL,
returnp_prefix TEXT  DEFAULT NULL,
expense_prefix TEXT  DEFAULT NULL,
item_addition INTEGER DEFAULT '0',
theme TEXT,
product_serial INTEGER,
default_discount INTEGER,
product_discount INTEGER DEFAULT '0',
discount_method INTEGER,
tax1 INTEGER,
tax2 INTEGER,
tax3 INTEGER,
overselling INTEGER DEFAULT '0',
restrict_user INTEGER DEFAULT '0',
restrict_calendar INTEGER DEFAULT '0',
timezone TEXT  DEFAULT NULL,
iwidth INTEGER DEFAULT '0',
iheight INTEGER,
twidth INTEGER,
theight INTEGER,
watermark INTEGER DEFAULT NULL,
reg_ver INTEGER DEFAULT NULL,
allow_reg INTEGER DEFAULT NULL,
reg_notification INTEGER DEFAULT NULL,
auto_reg INTEGER DEFAULT NULL,
protocol TEXT  DEFAULT 'mail',
mailpath TEXT  DEFAULT '/usr/sbin/sendmail',
smtp_host TEXT  DEFAULT NULL,
smtp_user TEXT  DEFAULT NULL,
smtp_pass TEXT  DEFAULT NULL,
smtp_port TEXT  DEFAULT '25',
smtp_crypto TEXT  DEFAULT NULL,
corn datetime DEFAULT NULL,
customer_group INTEGER,
default_email TEXT,
mmode INTEGER,
bc_fix INTEGER DEFAULT '0',
auto_detect_barcode INTEGER DEFAULT '0',
captcha INTEGER DEFAULT '1',
reference_format INTEGER DEFAULT '1',
racks INTEGER DEFAULT '0',
attributes INTEGER DEFAULT '0',
product_expiry INTEGER DEFAULT '0',
decimals INTEGER DEFAULT '2',
qty_decimals INTEGER DEFAULT '2',
decimals_sep TEXT  DEFAULT '.',
thousands_sep TEXT  DEFAULT ',',
invoice_view INTEGER DEFAULT '0',
default_biller INTEGER DEFAULT NULL,
envato_username TEXT  DEFAULT NULL,
purchase_code TEXT  DEFAULT NULL,
rtl INTEGER DEFAULT '0',
each_spent decimal(15,4) DEFAULT NULL,
ca_point INTEGER DEFAULT NULL,
each_sale decimal(15,4) DEFAULT NULL,
sa_point INTEGER DEFAULT NULL,
`update` INTEGER DEFAULT '0',
sac INTEGER DEFAULT '0',
display_all_products INTEGER DEFAULT '0',
display_symbol INTEGER DEFAULT NULL,
symbol TEXT  DEFAULT NULL,
remove_expired INTEGER DEFAULT '0',
barcode_separator TEXT  DEFAULT '_',
set_focus INTEGER DEFAULT '0',
price_group INTEGER DEFAULT NULL,
barcode_img INTEGER DEFAULT '1',
ppayment_prefix TEXT  DEFAULT 'POP',
disable_editing INTEGER DEFAULT '90',
qa_prefix TEXT  DEFAULT NULL,
update_cost INTEGER DEFAULT NULL,
apis INTEGER DEFAULT '0',
pdf_lib TEXT  DEFAULT NULL,
state TEXT  DEFAULT NULL,
sma_payment_prefix TEXT  DEFAULT NULL,
deposit_prefix TEXT  DEFAULT NULL,
cashier_close INTEGER DEFAULT '0',
alert_sale_expired INTEGER DEFAULT '0',
tipo_regimen INTEGER DEFAULT '1',
purchase_tax_rate INTEGER DEFAULT '1',
modulary INTEGER DEFAULT '0',
resolucion_porc_aviso decimal(4,2) DEFAULT '0.00',
resolucion_dias_aviso INTEGER DEFAULT '0',
prioridad_precios_producto INTEGER DEFAULT '1',
descuento_orden INTEGER DEFAULT '1',
allow_change_sale_iva INTEGER DEFAULT '0',
tax_rate_traslate INTEGER DEFAULT '0',
get_companies_check_digit INTEGER DEFAULT '1',
tipo_persona INTEGER,
tipo_documento TEXT,
digito_verificacion INTEGER DEFAULT NULL,
numero_documento TEXT,
razon_social TEXT,
nombre_comercial TEXT,
primer_nombre TEXT,
segundo_nombre TEXT,
primer_apellido TEXT,
segundo_apellido TEXT,
matricula_mercantil TEXT,
direccion TEXT,
localidad TEXT,
postal_code TEXT,
ciudad TEXT,
city_code TEXT  DEFAULT NULL,
departamento TEXT,
pais TEXT,
allow_advanced_search INTEGER DEFAULT '0',
rounding INTEGER DEFAULT '0',
purchase_payment_affects_cash_register INTEGER DEFAULT '2',
digital_signature TEXT,
max_num_results_display INTEGER DEFAULT '15',
cost_center_selection INTEGER DEFAULT '2',
hide_products_in_zero_price INTEGER DEFAULT '0',
default_cost_center INTEGER DEFAULT NULL,
tax_rate_translate INTEGER DEFAULT '0',
electronic_billing INTEGER DEFAULT '0',
fe_technology_provider INTEGER DEFAULT NULL,
fe_user TEXT  DEFAULT NULL,
fe_password TEXT  DEFAULT NULL,
tax_method INTEGER DEFAULT '2',
show_alert_sale_expired INTEGER DEFAULT '1',
customer_default_country TEXT  DEFAULT NULL,
customer_default_state TEXT  DEFAULT NULL,
customer_default_city TEXT  DEFAULT NULL,
set_adjustment_cost INTEGER DEFAULT '0',
default_records_filter INTEGER DEFAULT '0',
show_brand_in_product_search INTEGER DEFAULT '0',
close_year_step INTEGER DEFAULT '0',
closed_from_another_year INTEGER DEFAULT '0',
precios_por_unidad_presentacion INTEGER DEFAULT NULL,
lock_cost_field_in_product INTEGER DEFAULT '1',
fuente_retainer INTEGER DEFAULT '0',
iva_retainer INTEGER DEFAULT '0',
ica_retainer INTEGER DEFAULT '0',
export_to_csv_each_new_customer INTEGER DEFAULT '0',
commision_payment_method INTEGER DEFAULT '1',
default_expense_id_to_pay_commisions INTEGER DEFAULT NULL,
margin_price_formula INTEGER DEFAULT '0',
users_can_view_price_groups INTEGER DEFAULT '0',
users_can_view_warehouse_quantitys INTEGER DEFAULT '0',
product_variant_language TEXT  DEFAULT NULL,
product_variants_language TEXT  DEFAULT NULL,
send_electronic_invoice_to INTEGER DEFAULT '1',
copy_mail_to_sender INTEGER DEFAULT '0',
days_before_current_date INTEGER DEFAULT '0',
days_after_current_date INTEGER DEFAULT '0',
add_individual_attachments INTEGER DEFAULT '0',
product_crud_validate_cost INTEGER DEFAULT NULL,
alert_zero_cost_sale INTEGER DEFAULT NULL,
customer_branch_language TEXT  DEFAULT NULL,
customer_branches_language TEXT  DEFAULT NULL,
barcode_reader_exact_search INTEGER DEFAULT '0',
which_cost_margin_validation INTEGER DEFAULT '1',
max_minutes_random_pin_code INTEGER DEFAULT '5',
cron_job_db_backup INTEGER DEFAULT '1',
cron_job_images_backup INTEGER DEFAULT '1',
cron_job_ebilling_backup INTEGER DEFAULT '1',
cron_job_send_mail INTEGER DEFAULT '1',
fe_work_environment INTEGER DEFAULT '1',
fe_technical_annex_version INTEGER DEFAULT '1',
management_consecutive_suppliers INTEGER DEFAULT '0',
url_web TEXT  DEFAULT NULL,
profitability_margin_validation INTEGER DEFAULT NULL,
prorate_shipping_cost INTEGER DEFAULT '0',
session_expiration_time INTEGER DEFAULT '15',
product_order INTEGER DEFAULT '1',
keep_seller_from_user INTEGER DEFAULT '0',
invoice_values_greater_than_zero INTEGER DEFAULT '1',
except_category_taxes INTEGER DEFAULT '0',
category_tax_exception_start_date date DEFAULT NULL,
category_tax_exception_end_date date DEFAULT NULL,
category_tax_exception_tax_rate_id INTEGER DEFAULT NULL,
customer_territorial_decree_tax_rate_id INTEGER DEFAULT NULL,
ipoconsumo INTEGER DEFAULT NULL,
default_return_payment_method TEXT  DEFAULT '0',
manual_payment_reference INTEGER DEFAULT '0',
self_withholding_percentage decimal(25,4) DEFAULT '0.0000',
item_discount_apply_to INTEGER DEFAULT '2',
gift_card_language TEXT  DEFAULT NULL,
automatic_update INTEGER DEFAULT '0',
wappsi_rest_url TEXT,
dropbox_key TEXT, 
dropbox_secret TEXT, 
dropbox_token TEXT, 
detail_due_sales INTEGER DEFAULT '0',
detail_partial_sales INTEGER DEFAULT '0',
detail_paid_sales INTEGER DEFAULT '0',
detail_products_expirated INTEGER DEFAULT '0',
detail_products_promo_expirated INTEGER DEFAULT '0',
detail_sales_per_biller INTEGER DEFAULT '0',
detail_pos_registers INTEGER DEFAULT '0',
detail_zeta_report INTEGER DEFAULT '0',
great_contributor INTEGER DEFAULT '0',
annual_closure INTEGER DEFAULT '0',
product_variant_per_serial INTEGER DEFAULT '0',
product_search_show_quantity INTEGER DEFAULT '1',
suspended_sales_to_retail INTEGER DEFAULT '1',
payments_methods_retcom INTEGER DEFAULT '0',
product_default_exempt_tax_rate INTEGER,
ciiu_code TEXT DEFAULT NULL,
production_order_one_reference_limit INTEGER DEFAULT NULL,
system_start_date date DEFAULT '2018-01-01',
set_product_variant_suffix INTEGER DEFAULT '0',
disable_product_price_under_cost INTEGER DEFAULT '1',
wms_picking_filter_biller INTEGER DEFAULT '0',
accounting_year_suffix TEXT  DEFAULT NULL,
enable_customer_tax_exemption INTEGER DEFAULT '1',
management_order_sale_delivery_time INTEGER DEFAULT '0',
delivery_day_max_orders INTEGER DEFAULT NULL,
block_movements_from_another_year INTEGER DEFAULT '0',
product_transformation_validate_quantity INTEGER DEFAULT '1',
rete_other_language TEXT  DEFAULT NULL,
last_update datetime DEFAULT CURRENT_TIMESTAMP,
product_preferences_management INTEGER DEFAULT '1'
);
''';

const String DbAddressesSql = '''
CREATE TABLE sma_addresses (
id INTEGER PRIMARY KEY,
id_cloud INTEGER,
company_id INTEGER,
direccion TEXT,
sucursal TEXT  DEFAULT NULL,
city TEXT,
postal_code TEXT  DEFAULT NULL,
state TEXT,
country TEXT,
geo_location TEXT DEFAULT NULL,
latitude INTEGER DEFAULT NULL,
longitude INTEGER DEFAULT NULL,
phone TEXT  DEFAULT NULL,
updated_at timestamp,
city_code TEXT  DEFAULT NULL,
customer_address_seller_id_assigned INTEGER DEFAULT NULL,
customer_group_id INTEGER DEFAULT NULL,
customer_group_name TEXT  DEFAULT NULL,
price_group_id INTEGER DEFAULT NULL,
price_group_name TEXT  DEFAULT NULL,
seller_sale_comision decimal(25,4) DEFAULT '0.0000',
seller_collection_comision decimal(25,4) DEFAULT '0.0000',
code TEXT  DEFAULT NULL,
line1 TEXT  DEFAULT NULL,
line2 TEXT  DEFAULT NULL,
email TEXT  DEFAULT NULL,
vat_no TEXT  DEFAULT NULL,
location TEXT  DEFAULT NULL,
subzone TEXT  DEFAULT NULL,
last_update datetime DEFAULT CURRENT_TIMESTAMP
);
''';

const String DbUpdatesSql = '''
 CREATE TABLE sync (
id INTEGER,
last_update datetime DEFAULT NULL
);
''';

const String WarehouseProductsSql = '''
CREATE TABLE sma_warehouses_products (
id INTEGER PRIMARY KEY,
id_cloud INTEGER,
product_id INTEGER NOT NULL,
warehouse_id INTEGER NOT NULL,
quantity decimal(15,4) NOT NULL,
rack TEXT  DEFAULT NULL,
avg_cost decimal(25,4) NOT NULL,
closed_year INTEGER DEFAULT '0' ,
warehouse_location TEXT  DEFAULT NULL,
last_update datetime DEFAULT CURRENT_TIMESTAMP
);
''';
const String WarehousesSql = '''
CREATE TABLE `sma_warehouses` (
id INTEGER PRIMARY KEY,
id_cloud INTEGER NOT NULL ,
code TEXT  NOT NULL,
name TEXT  NOT NULL,
address TEXT  NOT NULL,
map TEXT  DEFAULT NULL,
phone TEXT  DEFAULT NULL,
email TEXT  DEFAULT NULL,
price_group_id INTEGER DEFAULT NULL,
status INTEGER DEFAULT '1' ,
type INTEGER DEFAULT '1' ,
preffix TEXT  DEFAULT NULL,
area TEXT  DEFAULT NULL,
street TEXT  DEFAULT NULL,
module TEXT  DEFAULT NULL,
level TEXT  DEFAULT NULL,
suffix TEXT  DEFAULT NULL,
last_update datetime DEFAULT CURRENT_TIMESTAMP
);

''';

const String BrandsSql = '''
CREATE TABLE sma_brands (
id INTEGER PRIMARY KEY,
id_cloud INTEGER,
code TEXT  DEFAULT NULL,
name TEXT  NOT NULL,
image TEXT  DEFAULT NULL,
slug TEXT  DEFAULT NULL,
last_update datetime DEFAULT CURRENT_TIMESTAMP
);
''';

const String PaymentMethodsSql = '''
CREATE TABLE sma_payment_methods (
id INTEGER PRIMARY KEY,
id_cloud INTEGER,
name TEXT  NOT NULL,
code TEXT  NOT NULL,
state_sale INTEGER NOT NULL DEFAULT '1' ,
state_purchase INTEGER NOT NULL DEFAULT '1' ,
code_fe TEXT  NOT NULL ,
cash_payment INTEGER DEFAULT '0' ,
due_payment INTEGER NOT NULL DEFAULT '0' ,
commision_value TEXT  DEFAULT NULL,
commision_ledger_id INTEGER DEFAULT NULL,
retefuente_value TEXT  DEFAULT NULL,
retefuente_ledger_id INTEGER DEFAULT NULL,
reteiva_value TEXT  DEFAULT NULL,
reteiva_ledger_id INTEGER DEFAULT NULL,
reteica_value TEXT  DEFAULT NULL,
reteica_ledger_id INTEGER DEFAULT NULL,
supplier_id INTEGER DEFAULT NULL,
icon TEXT  DEFAULT 'default.png',
biller_accountant_parametrization INTEGER DEFAULT '0' ,
billers text,
last_update datetime DEFAULT CURRENT_TIMESTAMP
);
''';

const String DbPosSettingsSql = '''
CREATE TABLE `sma_pos_settings` (
id INTEGER PRIMARY KEY,
pos_id INTEGER NOT NULL,
cat_limit INTEGER NOT NULL,
pro_limit INTEGER NOT NULL,
default_section INTEGER NOT NULL,
default_customer INTEGER NOT NULL,
default_biller INTEGER NOT NULL,
display_time TEXT  NOT NULL DEFAULT 'yes',
cf_title1 TEXT  DEFAULT NULL,
cf_title2 TEXT  DEFAULT NULL,
cf_value1 TEXT  DEFAULT NULL,
cf_value2 TEXT  DEFAULT NULL,
receipt_printer TEXT  DEFAULT NULL,
cash_drawer_codes TEXT  DEFAULT NULL,
focus_add_item TEXT  DEFAULT NULL,
add_manual_product TEXT  DEFAULT NULL,
customer_selection TEXT  DEFAULT NULL,
add_customer TEXT  DEFAULT NULL,
toggle_category_slider TEXT  DEFAULT NULL,
toggle_subcategory_slider TEXT  DEFAULT NULL,
cancel_sale TEXT  DEFAULT NULL,
suspend_sale TEXT  DEFAULT NULL,
print_items_list TEXT  DEFAULT NULL,
finalize_sale TEXT  DEFAULT NULL,
today_sale TEXT  DEFAULT NULL,
open_hold_bills TEXT  DEFAULT NULL,
close_register TEXT  DEFAULT NULL,
keyboard tinyINTEGER NOT NULL,
pos_printers TEXT  DEFAULT NULL,
java_applet tinyINTEGER NOT NULL,
product_button_color TEXT  NOT NULL DEFAULT 'default',
tooltips tinyINTEGER DEFAULT '1',
paypal_pro tinyINTEGER DEFAULT '0',
stripe tinyINTEGER DEFAULT '0',
rounding tinyINTEGER DEFAULT '0',
char_per_line tinyINTEGER DEFAULT '42',
pin_code TEXT  DEFAULT NULL,
purchase_code TEXT  DEFAULT 'purchase_code',
envato_username TEXT  DEFAULT 'envato_username',
version TEXT  DEFAULT '3.3.5',
after_sale_page tinyINTEGER DEFAULT '0',
item_order tinyINTEGER DEFAULT '0',
authorize tinyINTEGER DEFAULT '0',
toggle_brands_slider TEXT  DEFAULT NULL,
remote_printing tinyINTEGER DEFAULT '1',
printer INTEGER DEFAULT NULL,
order_printers TEXT  DEFAULT NULL,
auto_print tinyINTEGER DEFAULT '0',
customer_details tinyINTEGER DEFAULT NULL,
local_printers tinyINTEGER DEFAULT NULL,
balance_settings INTEGER DEFAULT '0' ,
balance_label_prefix TEXT  DEFAULT NULL,
time_focus_quantity decimal(6,4) DEFAULT '4.0000',
restobar_mode INTEGER DEFAULT '0' ,
table_service INTEGER DEFAULT '0' ,
order_print_mode INTEGER DEFAULT '0' ,
apply_suggested_tip decimal(25,4) DEFAULT '0.0000',
apply_suggested_home_delivery_amount decimal(25,4) DEFAULT '0.0000',
home_delivery_in_invoice INTEGER DEFAULT '1' ,
cloud_print_mail TEXT  DEFAULT NULL,
cloud_print_service_name TEXT  DEFAULT NULL,
cloud_print_json_name TEXT  DEFAULT NULL,
printer_selected_direct_printing INTEGER DEFAULT '0',
detail_sale_by_category INTEGER DEFAULT '0' ,
show_suspended_bills_automatically INTEGER DEFAULT '0' ,
print_voucher_delivery INTEGER DEFAULT '0',
allow_print_command INTEGER DEFAULT '0',
express_payment INTEGER DEFAULT '0' ,
search_product_price TEXT  DEFAULT NULL,
except_tip_restobar INTEGER DEFAULT '0' ,
required_shipping_restobar INTEGER DEFAULT '1',
mobile_print_automatically_invoice INTEGER DEFAULT '1' ,
use_barcode_scanner INTEGER NOT NULL DEFAULT '1' ,
product_clic_action INTEGER NOT NULL DEFAULT '1',
show_variants_and_preferences INTEGER NOT NULL DEFAULT '0',
order_to_table_default_restobar INTEGER NOT NULL DEFAULT '0' ,
mobile_print_wait_time decimal(6,4) DEFAULT '0.0000',
show_client_modal_on_select INTEGER DEFAULT '0' ,
last_update datetime DEFAULT CURRENT_TIMESTAMP
);

''';

const String DocumenTypesSql = '''
CREATE TABLE `sma_documentypes` (
id INTEGER PRIMARY KEY,
id_cloud INTEGER NOT NULL ,
nombre TEXT  NOT NULL,
abreviacion TEXT  NOT NULL,
codigo_doc INTEGER NOT NULL,
last_update datetime DEFAULT CURRENT_TIMESTAMP
);''';
const String CountriesSql = '''
CREATE TABLE `sma_countries` (
CODIGO TEXT NOT NULL DEFAULT '',
NOMBRE TEXT NOT NULL DEFAULT '',
INDICATIVO TEXT NOT NULL DEFAULT '',
MONEDA INTEGER NOT NULL DEFAULT '0',
codigo_iso TEXT NOT NULL
);''';
const String StatesSql = '''
CREATE TABLE `sma_states` (
CODDEPARTAMENTO TEXT NOT NULL DEFAULT '',
DEPARTAMENTO TEXT NOT NULL DEFAULT '',
PAIS TEXT NOT NULL DEFAULT '',
DESADICIONAL TEXT DEFAULT ''
);
''';

const String CitysSql = '''
CREATE TABLE `sma_cities` (
PAIS TEXT NOT NULL DEFAULT '""',
CODDEPARTAMENTO TEXT DEFAULT '""',
DEPARTAMENTO TEXT DEFAULT NULL,
CODIGO TEXT NOT NULL DEFAULT '',
DESCRIPCION TEXT NOT NULL DEFAULT ''
);
''';

const String DocumentTypesSql = '''
CREATE TABLE `sma_documents_types` (
id INTEGER PRIMARY KEY ,
id_cloud INTEGER NOT NULL,
module INTEGER NOT NULL ,
nombre TEXT  DEFAULT NULL,
factura_electronica tinyINTEGER DEFAULT '0' ,
factura_contingencia tinyINTEGER DEFAULT NULL ,
num_resolucion TEXT  DEFAULT NULL,
palabra_resolucion INTEGER DEFAULT '1',
sales_prefix TEXT  DEFAULT NULL,
sales_consecutive bigINTEGER DEFAULT NULL,
inicio_resolucion TEXT  DEFAULT NULL,
fin_resolucion TEXT  DEFAULT NULL,
emision_resolucion date DEFAULT NULL,
vencimiento_resolucion date DEFAULT NULL,
clave_tecnica TEXT  DEFAULT NULL,
fe_work_environment tinyINTEGER DEFAULT '0' ,
fe_testid TEXT  DEFAULT NULL ,
invoice_footer mediumtext,
key_log INTEGER DEFAULT '1',
module_invoice_format_id INTEGER DEFAULT NULL,
save_resolution_in_sale INTEGER DEFAULT '1' ,
word_type_sale TEXT  DEFAULT NULL,
fe_transaction_id TEXT  DEFAULT NULL ,
not_accounting INTEGER DEFAULT '0' ,
invoice_header mediumtext,
add_consecutive_left_zeros INTEGER DEFAULT '1',
last_update datetime DEFAULT CURRENT_TIMESTAMP
);
''';

const String BillerDocumentTypesSql = '''
CREATE TABLE `sma_biller_documents_types` (
id INTEGER NOT NULL,
biller_id INTEGER NOT NULL,
document_type_id INTEGER NOT NULL
);
''';

const String PCategoriesSql = '''
CREATE TABLE `sma_categories` (
id INTEGER PRIMARY KEY,
id_cloud INTEGER NOT NULL,
code TEXT  NOT NULL,
name TEXT  NOT NULL,
image TEXT  DEFAULT NULL,
parent_id INTEGER DEFAULT NULL,
slug TEXT  DEFAULT NULL,
printer_id INTEGER DEFAULT NULL,
preparer_id INTEGER DEFAULT NULL,
hide INTEGER DEFAULT '0',
profitability_margin decimal(5,2) DEFAULT '0.00',
profitability_margin_price_base decimal(5,2) DEFAULT '0.00',
except_category_taxes INTEGER DEFAULT '0' ,
preparation_area_id INTEGER DEFAULT NULL,
last_update datetime DEFAULT CURRENT_TIMESTAMP
);
''';

const String PUnitsSql = '''

CREATE TABLE `sma_units` (
id INTEGER PRIMARY KEY ,
id_cloud INTEGER NOT NULL ,
code TEXT  NOT NULL,
name TEXT  NOT NULL,
base_unit INTEGER DEFAULT NULL,
operator TEXT  DEFAULT NULL,
unit_value TEXT  DEFAULT NULL,
operation_value decimal(25,4) DEFAULT NULL,
price_group_id INTEGER DEFAULT NULL,
last_update datetime DEFAULT CURRENT_TIMESTAMP
);
''';

const String GroupsSql = '''
CREATE TABLE `sma_groups` (
id INTEGER PRIMARY KEY,
id_cloud INTEGER NOT NULL,
name TEXT  NOT NULL,
description TEXT  NOT NULL,
relationed_companies INTEGER DEFAULT '0',
group_name_relationed TEXT  DEFAULT NULL,
last_update datetime NOT NULL DEFAULT CURRENT_TIMESTAMP
);''';

//______________________________________________________________________________________________________________
//
//                                       SUSPENDED SALES LOCALLY SAVED
//_______________________________________________________________________________________________________________

/// ONLY TO MANAGE SUSPENDED SALES LOCALLY

const String SuspendedSalesSql = '''
CREATE TABLE `suspended_sales` (
id INTEGER PRIMARY KEY,
key_word TEXT,
id_customer INTEGER,
id_address INTEGER NOT NULL,
id_pay_document INTEGER,
id_pay_method INTEGER,
pay_value INTEGER,
invoice_note TEXT,
seller_name TEXT,
dispatch_note TEXT,
customer_name TEXT NOT NULL,
items INTEGER NOT NULL,
total_value decimal(25,4),
status INTEGER NOT NULL,
created_date datetime NOT NULL DEFAULT CURRENT_TIMESTAMP
);
''';
const String SuspendedSaleProductsSql = '''
CREATE TABLE `suspended_sales_product` (
id INTEGER PRIMARY KEY,
id_suspended_sale INTEGER NOT NULL,
id_product INTEGER NOT NULL,
quantity INTEGER NOT NULL,
price decimal(25,4),
price_policy decimal(25,4),
price_without_discount decimal(25,4),
discount decimal(25,4),
unit_id INTEGER DEFAULT NULL
);
''';
//-----------------------------------------------------------------------------
//                            SALES SAVED IN LOCAL DB
//
//-----------------------------------------------------------------------------

/// Locally saved sales
const String SalesSql = '''
CREATE TABLE `sma_sales` (
`id` INTEGER PRIMARY KEY,
`id_cloud` INTEGER,
`date` datetime DEFAULT NULL,
`reference_no` TEXT  NOT NULL,
`customer_id` INTEGER NOT NULL,
`customer` TEXT  NOT NULL,
`biller_id` INTEGER NOT NULL,
`biller` TEXT  NOT NULL,
`warehouse_id` INTEGER DEFAULT NULL,
`note` TEXT  DEFAULT NULL,
`staff_note` TEXT  DEFAULT NULL,
`total` decimal(25,4) NOT NULL,
`product_discount` decimal(25,4) DEFAULT '0.0000',
`order_discount_id` TEXT  DEFAULT NULL,
`total_discount` decimal(25,4) DEFAULT '0.0000',
`order_discount` decimal(25,4) DEFAULT '0.0000',
`product_tax` decimal(25,4) DEFAULT '0.0000',
`order_tax_id` INTEGER DEFAULT NULL,
`order_tax` decimal(25,4) DEFAULT '0.0000',
`total_tax` decimal(25,4) DEFAULT '0.0000',
`shipping` decimal(25,4) DEFAULT '0.0000',
`grand_total` decimal(25,4) NOT NULL,
`sale_status` TEXT  DEFAULT NULL ,
`payment_status` TEXT  DEFAULT NULL ,
`payment_term` tinyINTEGER DEFAULT NULL,
`due_date` date DEFAULT NULL,
`created_by` INTEGER DEFAULT NULL,
`updated_by` INTEGER DEFAULT NULL,
`updated_at` timestamp NULL DEFAULT NULL,
`total_items` smallINTEGER DEFAULT NULL,
`pos` tinyINTEGER NOT NULL DEFAULT '0',
`paid` decimal(25,4) DEFAULT '0.0000',
`return_id` INTEGER DEFAULT NULL,
`surcharge` decimal(25,4) NOT NULL DEFAULT '0.0000',
`attachment` TEXT  DEFAULT NULL,
`return_sale_ref` TEXT  DEFAULT NULL,
`sale_id` INTEGER DEFAULT NULL,
`return_sale_total` decimal(25,4) NOT NULL DEFAULT '0.0000',
`rounding` decimal(10,4) DEFAULT NULL,
`suspend_note` TEXT  DEFAULT NULL,
`api` tinyINTEGER DEFAULT '0',
`shop` tinyINTEGER DEFAULT '0',
`address_id` INTEGER DEFAULT NULL,
`seller_id` INTEGER DEFAULT NULL,
`reserve_id` INTEGER DEFAULT NULL,
`hash` TEXT  DEFAULT NULL,
`manual_payment` TEXT  DEFAULT NULL,
`cgst` decimal(25,4) DEFAULT NULL,
`sgst` decimal(25,4) DEFAULT NULL,
`igst` decimal(25,4) DEFAULT NULL,
`payment_method` TEXT  DEFAULT '',
`pay_partner` smallINTEGER  NOT NULL DEFAULT '0' ,
`rete_fuente_percentage` decimal(6,3) DEFAULT '0.000',
`rete_fuente_total` decimal(25,4) DEFAULT '0.0000',
`rete_fuente_account` INTEGER DEFAULT '0',
`rete_fuente_base` decimal(25,4) DEFAULT NULL,
`rete_iva_percentage` decimal(6,3) DEFAULT '0.000',
`rete_iva_total` decimal(25,4) DEFAULT '0.0000',
`rete_iva_account` INTEGER DEFAULT '0',
`rete_iva_base` decimal(25,4) DEFAULT NULL,
`rete_ica_percentage` decimal(6,3) DEFAULT '0.000',
`rete_ica_total` decimal(25,4) DEFAULT '0.0000',
`rete_ica_account` INTEGER DEFAULT '0',
`rete_ica_base` decimal(25,4) DEFAULT NULL,
`rete_other_percentage` decimal(6,3) DEFAULT '0.000',
`rete_other_total` decimal(25,4) DEFAULT '0.0000',
`rete_other_account` INTEGER DEFAULT '0',
`rete_other_base` decimal(25,4) DEFAULT NULL,
`resolucion` TEXT  DEFAULT NULL,
`fe_correo_enviado` tinyINTEGER NOT NULL DEFAULT '0' ,
`fe_aceptado` tinyINTEGER NOT NULL DEFAULT '0' ,
`fe_recibido` tinyINTEGER DEFAULT NULL ,
`cufe` TEXT  DEFAULT NULL ,
`codigo_qr` TEXT  DEFAULT NULL ,
`fe_id_transaccion` TEXT  DEFAULT NULL ,
`fe_mensaje` TEXT  DEFAULT NULL ,
`fe_mensaje_soporte_tecnico` mediumtext  ,
`fe_xml` TEXT  ,
`fe_debit_credit_note_concept_dian_code` INTEGER DEFAULT NULL ,
`sale_currency` TEXT  DEFAULT NULL,
`sale_currency_trm` decimal(25,4) DEFAULT NULL,
`cost_center_id` INTEGER DEFAULT NULL,
`document_type_id` INTEGER DEFAULT NULL,
`payment_method_fe` INTEGER NOT NULL ,
`payment_mean_fe` TEXT  NOT NULL ,
`tip_amount` decimal(25,4) DEFAULT '0.0000',
`shipping_in_grand_total` INTEGER DEFAULT '1' ,
`sale_origin` TEXT  DEFAULT NULL,
`sale_origin_reference_no` TEXT  DEFAULT NULL,
`rete_fuente_id` INTEGER DEFAULT NULL,
`rete_iva_id` INTEGER DEFAULT NULL,
`rete_ica_id` INTEGER DEFAULT NULL,
`rete_other_id` INTEGER DEFAULT NULL,
`sale_comm_perc` decimal(5,2) DEFAULT '0.00',
`collection_comm_perc` decimal(5,2) DEFAULT '0.00',
`sale_comm_amount` decimal(25,4) DEFAULT '0.0000',
`sale_comm_payment_status` INTEGER DEFAULT '0',
`debit_note_id` INTEGER DEFAULT NULL ,
`reference_debit_note` TEXT  DEFAULT NULL ,
`reference_invoice_id` INTEGER DEFAULT NULL ,
`restobar_table_id` INTEGER DEFAULT NULL,
`consumption_sales` decimal(25,4) DEFAULT NULL,
`self_withholding_amount` decimal(25,4) DEFAULT '0.0000',
`self_withholding_percentage` decimal(25,4) DEFAULT '0.0000',
`printed` tinyINTEGER NOT NULL DEFAULT '0' ,
`due_payment_method_id` INTEGER DEFAULT NULL,
`registration_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
`return_other_concepts` tinyINTEGER NOT NULL DEFAULT '0' ,
`rete_bomberil_percentage` decimal(6,3) DEFAULT '0.000',
`rete_bomberil_total` decimal(25,4) DEFAULT '0.0000',
`rete_bomberil_account` INTEGER DEFAULT '0',
`rete_bomberil_base` decimal(25,4) DEFAULT NULL,
`rete_autoaviso_percentage` decimal(6,3) DEFAULT '0.000',
`rete_autoaviso_total` decimal(25,4) DEFAULT '0.0000',
`rete_autoaviso_account` INTEGER DEFAULT '0',
`rete_autoaviso_base` decimal(25,4) DEFAULT NULL,
`rete_autoica_percentage` decimal(6,3) DEFAULT '0.000',
`rete_autoica_total` decimal(25,4) DEFAULT '0.0000',
`rete_autoica_account` INTEGER DEFAULT '0',
`rete_autoica_base` decimal(25,4) DEFAULT NULL,
`rete_autoica_account_counterpart` INTEGER DEFAULT '0',
`rete_autoaviso_account_counterpart` INTEGER DEFAULT '0',
`rete_bomberil_account_counterpart` INTEGER DEFAULT '0',
`rete_bomberil_id` INTEGER DEFAULT NULL,
`rete_autoaviso_id` INTEGER DEFAULT NULL
);
''';

const String SaleItemsSql = '''
CREATE TABLE `sma_sale_items` (
`id` INTEGER PRIMARY KEY,
`sale_id` INTEGER  NOT NULL,
`product_id` INTEGER  NOT NULL,
`product_code` TEXT  NOT NULL,
`product_name` TEXT  NOT NULL,
`product_type` TEXT  DEFAULT NULL,
`option_id` INTEGER DEFAULT NULL,
`net_unit_price` decimal(25,4) NOT NULL,
`unit_price` decimal(25,4) DEFAULT NULL,
`quantity` decimal(15,4) NOT NULL,
`warehouse_id` INTEGER DEFAULT NULL,
`item_tax` decimal(25,4) DEFAULT NULL,
`tax_rate_id` INTEGER DEFAULT NULL,
`tax` TEXT  DEFAULT NULL,
`item_tax_2` decimal(25,4) DEFAULT NULL,
`tax_rate_2_id` INTEGER DEFAULT NULL,
`tax_2` TEXT  DEFAULT NULL,
`discount` TEXT  DEFAULT NULL,
`item_discount` decimal(25,4) DEFAULT NULL,
`subtotal` decimal(25,4) NOT NULL,
`serial_no` TEXT  DEFAULT NULL,
`real_unit_price` decimal(25,4) DEFAULT NULL,
`sale_item_id` INTEGER DEFAULT NULL,
`product_unit_id` INTEGER DEFAULT NULL,
`product_unit_code` TEXT  DEFAULT NULL,
`unit_quantity` decimal(15,4) NOT NULL,
`comment` TEXT  DEFAULT NULL,
`gst` TEXT  DEFAULT NULL,
`cgst` decimal(25,4) DEFAULT NULL,
`sgst` decimal(25,4) DEFAULT NULL,
`igst` decimal(25,4) DEFAULT NULL,
`unit_order_discount` decimal(25,4) DEFAULT NULL,
`avg_net_unit_cost` decimal(25,4) DEFAULT NULL,
`state_readiness` tinyINTEGER NOT NULL DEFAULT '1' ,
`preferences` TEXT  DEFAULT NULL,
`price_before_tax` decimal(25,4) DEFAULT '0.0000',
`product_unit_id_selected` INTEGER DEFAULT NULL,
`consumption_sales` decimal(25,4) DEFAULT NULL,
`consumption_sales_costing` decimal(25,4) DEFAULT NULL,
`returned_quantity` decimal(15,4) DEFAULT NULL,
`price_before_promo` decimal(25,4) DEFAULT '0.0000',
`registration_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
`under_cost_authorized` INTEGER DEFAULT '0'
);
''';

const String PaymentSql = '''
CREATE TABLE `sma_payments` (
`id` INTEGER PRIMARY KEY,
`date` timestamp DEFAULT CURRENT_TIMESTAMP,
`sale_id` INTEGER DEFAULT NULL,
`return_id` INTEGER DEFAULT NULL,
`purchase_id` INTEGER DEFAULT NULL,
`expense_id` INTEGER DEFAULT NULL,
`reference_no` TEXT  DEFAULT NULL,
`transaction_id` TEXT  DEFAULT NULL,
`paid_by` text  NOT NULL,
`cheque_no` TEXT  DEFAULT NULL,
`cc_no` TEXT  DEFAULT NULL,
`cc_holder` TEXT  DEFAULT NULL,
`cc_month` TEXT  DEFAULT NULL,
`cc_year` TEXT  DEFAULT NULL,
`cc_type` TEXT  DEFAULT NULL,
`amount` decimal(25,4) NOT NULL,
`currency` TEXT  DEFAULT NULL,
`created_by` INTEGER NOT NULL,
`attachment` TEXT  DEFAULT NULL,
`type` TEXT  NOT NULL,
`note` TEXT  DEFAULT NULL,
`pos_paid` decimal(25,4) DEFAULT '0.0000',
`pos_balance` decimal(25,4) DEFAULT '0.0000',
`approval_code` TEXT  DEFAULT NULL,
`affect` INTEGER NOT NULL DEFAULT '0' ,
`trm_difference` decimal(25,4) DEFAULT '0.0000',
`trm_difference_ledger_id` INTEGER DEFAULT NULL,
`tax_rate_traslate` decimal(25,4) DEFAULT '0.0000',
`tax_rate_traslate_ledger_id` INTEGER DEFAULT NULL,
`cost_center_id` INTEGER DEFAULT NULL,
`rete_fuente_total` decimal(25,4) DEFAULT '0.0000',
`rete_iva_total` decimal(25,4) DEFAULT '0.0000',
`rete_ica_total` decimal(25,4) DEFAULT '0.0000',
`rete_other_total` decimal(25,4) DEFAULT '0.0000',
`multi_payment` INTEGER DEFAULT '0' ,
`mean_payment_code_fe` TEXT  NOT NULL ,
`payment_date` timestamp NULL DEFAULT NULL,
`consecutive_payment` TEXT  DEFAULT NULL,
`document_type_id` INTEGER DEFAULT NULL,
`rete_fuente_percentage` decimal(6,3) DEFAULT '0.000',
`rete_fuente_account` INTEGER DEFAULT '0',
`rete_fuente_base` decimal(25,4) DEFAULT NULL,
`rete_iva_percentage` decimal(6,3) DEFAULT '0.000',
`rete_iva_account` INTEGER DEFAULT '0',
`rete_iva_base` decimal(25,4) DEFAULT NULL,
`rete_ica_percentage` decimal(6,3) DEFAULT '0.000',
`rete_ica_account` INTEGER DEFAULT '0',
`rete_ica_base` decimal(25,4) DEFAULT NULL,
`rete_other_percentage` decimal(6,3) DEFAULT '0.000',
`rete_other_account` INTEGER DEFAULT '0',
`rete_other_base` decimal(25,4) DEFAULT NULL,
`rete_fuente_id` INTEGER DEFAULT NULL,
`rete_iva_id` INTEGER DEFAULT NULL,
`rete_ica_id` INTEGER DEFAULT NULL,
`rete_other_id` INTEGER DEFAULT NULL,
`discount_ledger_id` INTEGER DEFAULT NULL,
`comm_perc` decimal(7,4) DEFAULT '0.0000',
`comm_base` decimal(25,4) DEFAULT '0.0000',
`comm_amount` decimal(25,4) DEFAULT '0.0000',
`seller_id` INTEGER DEFAULT NULL,
`comm_payment_status` INTEGER DEFAULT '0',
`comm_payment_date` timestamp NULL DEFAULT NULL,
`comm_payment_reference_no` TEXT  DEFAULT NULL,
`concept_ledger_id` INTEGER DEFAULT NULL,
`affected_deposit_id` INTEGER DEFAULT NULL,
`return_reference_no` TEXT  DEFAULT NULL,
`pm_commision_value` TEXT  DEFAULT NULL,
`pm_retefuente_value` TEXT  DEFAULT NULL,
`pm_reteiva_value` TEXT  DEFAULT NULL,
`pm_reteica_value` TEXT  DEFAULT NULL,
`company_id` INTEGER DEFAULT NULL,
`rete_fuente_assumed` INTEGER DEFAULT NULL,
`rete_iva_assumed` INTEGER DEFAULT NULL,
`rete_ica_assumed` INTEGER DEFAULT NULL,
`rete_other_assumed` INTEGER DEFAULT NULL,
`rete_fuente_assumed_account` INTEGER DEFAULT NULL,
`rete_iva_assumed_account` INTEGER DEFAULT NULL,
`rete_ica_assumed_account` INTEGER DEFAULT NULL,
`rete_other_assumed_account` INTEGER DEFAULT NULL,
`concept_base` decimal(25,4) DEFAULT NULL,
`concept_company_id` INTEGER DEFAULT NULL,
`rete_bomberil_percentage` decimal(6,3) DEFAULT '0.000',
`rete_bomberil_total` decimal(25,4) DEFAULT '0.0000',
`rete_bomberil_account` INTEGER DEFAULT '0',
`rete_bomberil_base` decimal(25,4) DEFAULT NULL,
`rete_autoaviso_percentage` decimal(6,3) DEFAULT '0.000',
`rete_autoaviso_total` decimal(25,4) DEFAULT '0.0000',
`rete_autoaviso_account` INTEGER DEFAULT '0',
`rete_autoaviso_base` decimal(25,4) DEFAULT NULL,
`rete_bomberil_id` INTEGER DEFAULT NULL,
`rete_autoaviso_id` INTEGER DEFAULT NULL,
`rete_bomberil_assumed_account` INTEGER DEFAULT NULL,
`rete_autoaviso_assumed_account` INTEGER DEFAULT NULL,
`comm_paid_payments_ids` INTEGER DEFAULT NULL,
`comm_paid_sale_reference` TEXT  DEFAULT NULL
);

''';

const String FavotitesSql = '''

CREATE TABLE `sma_wishlist` (
`id` INTEGER NOT NULL PRIMARY KEY,
`id_cloud` INTEGER NOT NULL ,
`user_id` INTEGER,
`customer_id` INTEGER DEFAULT NULL,
`product_id` INTEGER DEFAULT NULL
);
''';

const String UnitPricesSql = '''

CREATE TABLE `sma_unit_prices` (
`id` INTEGER NOT NULL,
`code` INTEGER NOT NULL DEFAULT '0',
`valor_unitario` decimal(25,4) DEFAULT '0.0000',
`label` TEXT NOT NULL DEFAULT '0',
`unidad` TEXT NOT NULL DEFAULT '0',
`cantidad` decimal(15,4) DEFAULT '0.0000',
`unit_id` INTEGER NOT NULL DEFAULT '0',
`id_product` INTEGER DEFAULT NULL,
`price_group_id` INTEGER DEFAULT NULL,
`last_update` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP
);
''';

const String OrderSaleItemsSql = '''
CREATE TABLE `sma_order_sale_items` (
`id` INTEGER NOT NULL PRIMARY KEY,
`sale_id` INTEGER  NOT NULL,
`product_id` INTEGER  NOT NULL,
`product_code` TEXT  NOT NULL,
`product_name` TEXT  NOT NULL,
`product_type` TEXT  DEFAULT NULL,
`option_id` INTEGER DEFAULT NULL,
`net_unit_price` decimal(25,4) NOT NULL,
`unit_price` decimal(25,4) DEFAULT NULL,
`quantity` decimal(15,4) NOT NULL,
`quantity_to_bill` decimal(15,4) DEFAULT '0.0000',
`quantity_delivered` decimal(15,4) NOT NULL,
`warehouse_id` INTEGER DEFAULT NULL,
`item_tax` decimal(25,4) DEFAULT NULL,
`tax_rate_id` INTEGER DEFAULT NULL,
`tax` TEXT  DEFAULT NULL,
`item_tax_2` decimal(25,4) DEFAULT NULL,
`tax_rate_2_id` INTEGER DEFAULT NULL,
`tax_2` TEXT  DEFAULT NULL,
`discount` TEXT  DEFAULT NULL,
`item_discount` decimal(25,4) DEFAULT NULL,
`subtotal` decimal(25,4) NOT NULL,
`serial_no` TEXT  DEFAULT NULL,
`real_unit_price` decimal(25,4) DEFAULT NULL,
`sale_item_id` INTEGER DEFAULT NULL,
`product_unit_id` INTEGER DEFAULT NULL,
`product_unit_code` TEXT  DEFAULT NULL,
`unit_quantity` decimal(15,4) NOT NULL,
`comment` TEXT  DEFAULT NULL,
`gst` TEXT  DEFAULT NULL,
`cgst` decimal(25,4) DEFAULT NULL,
`sgst` decimal(25,4) DEFAULT NULL,
`igst` decimal(25,4) DEFAULT NULL,
`unit_order_discount` decimal(25,4) DEFAULT NULL,
`price_before_tax` decimal(25,4) DEFAULT '0.0000',
`preferences` TEXT  DEFAULT NULL,
`registration_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);
''';

const String OrderSalesSql = '''
CREATE TABLE `sma_order_sales` (
`id` INTEGER NOT NULL PRIMARY KEY,
`id_cloud` INTEGER NOT NULL ,
`date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
`reference_no` TEXT  NOT NULL,
`customer_id` INTEGER NOT NULL,
`customer` TEXT  NOT NULL,
`biller_id` INTEGER NOT NULL,
`biller` TEXT  NOT NULL,
`warehouse_id` INTEGER DEFAULT NULL,
`note` TEXT  DEFAULT NULL,
`staff_note` TEXT  DEFAULT NULL,
`total` decimal(25,4) NOT NULL,
`product_discount` decimal(25,4) DEFAULT '0.0000',
`order_discount_id` TEXT  DEFAULT NULL,
`total_discount` decimal(25,4) DEFAULT '0.0000',
`order_discount` decimal(25,4) DEFAULT '0.0000',
`product_tax` decimal(25,4) DEFAULT '0.0000',
`order_tax_id` INTEGER DEFAULT NULL,
`order_tax` decimal(25,4) DEFAULT '0.0000',
`total_tax` decimal(25,4) DEFAULT '0.0000',
`shipping` decimal(25,4) DEFAULT '0.0000',
`grand_total` decimal(25,4) NOT NULL,
`sale_status` TEXT  DEFAULT NULL ,
`payment_status` TEXT  DEFAULT NULL ,
`payment_term` tinyINTEGER DEFAULT NULL,
`due_date` date DEFAULT NULL,
`created_by` INTEGER DEFAULT NULL,
`updated_by` INTEGER DEFAULT NULL,
`updated_at` timestamp NULL DEFAULT NULL,
`total_items` smallINTEGER DEFAULT NULL,
`pos` tinyINTEGER NOT NULL DEFAULT '0',
`paid` decimal(25,4) DEFAULT '0.0000',
`return_id` INTEGER DEFAULT NULL,
`surcharge` decimal(25,4) NOT NULL DEFAULT '0.0000',
`attachment` TEXT  DEFAULT NULL,
`return_sale_ref` TEXT  DEFAULT NULL,
`sale_id` INTEGER DEFAULT NULL,
`return_sale_total` decimal(25,4) NOT NULL DEFAULT '0.0000',
`rounding` decimal(10,4) DEFAULT NULL,
`suspend_note` TEXT  DEFAULT NULL,
`api` tinyINTEGER DEFAULT '0',
`shop` tinyINTEGER DEFAULT '0',
`seller_id` INTEGER NOT NULL,
`address_id` INTEGER DEFAULT NULL,
`reserve_id` INTEGER DEFAULT NULL,
`hash` TEXT  DEFAULT NULL,
`manual_payment` TEXT  DEFAULT NULL,
`cgst` decimal(25,4) DEFAULT NULL,
`sgst` decimal(25,4) DEFAULT NULL,
`igst` decimal(25,4) DEFAULT NULL,
`payment_method` TEXT  DEFAULT "",
`pay_partner` smallINTEGER  NOT NULL DEFAULT '0' ,
`rete_fuente_percentage` decimal(6,3) DEFAULT '0.000',
`rete_fuente_total` decimal(25,4) DEFAULT '0.0000',
`rete_fuente_account` INTEGER DEFAULT '0',
`rete_fuente_base` decimal(25,4) DEFAULT NULL,
`rete_iva_percentage` decimal(6,3) DEFAULT '0.000',
`rete_iva_total` decimal(25,4) DEFAULT '0.0000',
`rete_iva_account` INTEGER DEFAULT '0',
`rete_iva_base` decimal(25,4) DEFAULT NULL,
`rete_ica_percentage` decimal(6,3) DEFAULT '0.000',
`rete_ica_total` decimal(25,4) DEFAULT '0.0000',
`rete_ica_account` INTEGER DEFAULT '0',
`rete_ica_base` decimal(25,4) DEFAULT NULL,
`rete_other_percentage` decimal(6,3) DEFAULT '0.000',
`rete_other_total` decimal(25,4) DEFAULT '0.0000',
`rete_other_account` INTEGER DEFAULT '0',
`rete_other_base` decimal(25,4) DEFAULT NULL,
`resolucion` TEXT  DEFAULT NULL,
`document_type_id` INTEGER DEFAULT NULL,
`destination_reference_no` TEXT  DEFAULT NULL,
`registration_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
`wms_picking_status` TEXT  DEFAULT NULL,
`delivery_time_id` INTEGER DEFAULT NULL,
`delivery_day` TEXT DEFAULT NULL,
`delivery_text` TEXT DEFAULT NULL,
`wms_packing_status` TEXT  DEFAULT NULL
);

''';

const String ErrorsDataSql = '''
CREATE TABLE `errors_log` (
  `id` INTEGER NOT NULL PRIMARY KEY,
  `error` TEXT NOT NULL ,
  `from` TEXT NOT NULL ,
  `date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);
''';

const String QuotesTableSql = '''
  CREATE TABLE `sma_quotes` (
  `id` INTEGER NOT NULL PRIMARY KEY,
  `id_cloud` INTEGER NOT NULL,
  `date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `reference_no` TEXT  NOT NULL,
  `customer_id` INTEGER NOT NULL,
  `customer` TEXT  NOT NULL,
  `warehouse_id` INTEGER DEFAULT NULL,
  `biller_id` INTEGER NOT NULL,
  `biller` TEXT  NOT NULL,
  `note` TEXT  DEFAULT NULL,
  `internal_note` TEXT  DEFAULT NULL,
  `total` decimal(25,4) NOT NULL,
  `product_discount` decimal(25,4) DEFAULT '0.0000',
  `order_discount` decimal(25,4) DEFAULT NULL,
  `order_discount_id` TEXT  DEFAULT NULL,
  `total_discount` decimal(25,4) DEFAULT '0.0000',
  `product_tax` decimal(25,4) DEFAULT '0.0000',
  `order_tax_id` INTEGER DEFAULT NULL,
  `order_tax` decimal(25,4) DEFAULT NULL,
  `total_tax` decimal(25,4) DEFAULT NULL,
  `shipping` decimal(25,4) DEFAULT '0.0000',
  `grand_total` decimal(25,4) NOT NULL,
  `status` TEXT  DEFAULT NULL,
  `created_by` INTEGER DEFAULT NULL,
  `updated_by` INTEGER DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `attachment` TEXT  DEFAULT NULL,
  `supplier_id` INTEGER DEFAULT NULL,
  `supplier` TEXT  DEFAULT NULL,
  `hash` TEXT  DEFAULT NULL,
  `cgst` decimal(25,4) DEFAULT NULL,
  `sgst` decimal(25,4) DEFAULT NULL,
  `igst` decimal(25,4) DEFAULT NULL,
  `quote_currency` TEXT  DEFAULT NULL,
  `quote_currency_trm` decimal(25,4) DEFAULT NULL,
  `quote_type` INTEGER DEFAULT '1' ,
  `rete_fuente_percentage` decimal(6,3) DEFAULT '0.000',
  `rete_fuente_total` decimal(25,4) DEFAULT '0.0000',
  `rete_fuente_account` INTEGER DEFAULT '0',
  `rete_fuente_base` decimal(25,4) DEFAULT NULL,
  `rete_iva_percentage` decimal(6,3) DEFAULT '0.000',
  `rete_iva_total` decimal(25,4) DEFAULT '0.0000',
  `rete_iva_account` INTEGER DEFAULT '0',
  `rete_iva_base` decimal(25,4) DEFAULT NULL,
  `rete_ica_percentage` decimal(6,3) DEFAULT '0.000',
  `rete_ica_total` decimal(25,4) DEFAULT '0.0000',
  `rete_ica_account` INTEGER DEFAULT '0',
  `rete_ica_base` decimal(25,4) DEFAULT NULL,
  `rete_other_percentage` decimal(6,3) DEFAULT '0.000',
  `rete_other_total` decimal(25,4) DEFAULT '0.0000',
  `rete_other_account` INTEGER DEFAULT '0',
  `rete_other_base` decimal(25,4) DEFAULT NULL,
  `rete_fuente_id` INTEGER DEFAULT NULL,
  `rete_iva_id` INTEGER DEFAULT NULL,
  `rete_ica_id` INTEGER DEFAULT NULL,
  `rete_other_id` INTEGER DEFAULT NULL,
  `address_id` INTEGER DEFAULT NULL,
  `seller_id` INTEGER DEFAULT NULL,
  `document_type_id` INTEGER DEFAULT NULL,
  `destination_reference_no` TEXT  DEFAULT NULL,
  `payment_status` INTEGER NOT NULL DEFAULT '0' ,
  `payment_term` INTEGER NOT NULL,
  `payment_method` TEXT  NOT NULL
  );
''';

const String QuoteItemsTableSql = '''
  CREATE TABLE `sma_quote_items` (
  `id` INTEGER NOT NULL PRIMARY KEY,
  `quote_id` INTEGER NOT NULL,
  `product_id` INTEGER NOT NULL,
  `product_code` TEXT  NOT NULL,
  `product_name` TEXT  NOT NULL,
  `product_type` TEXT  DEFAULT NULL,
  `option_id` INTEGER DEFAULT NULL,
  `net_unit_price` decimal(25,4) NOT NULL,
  `unit_price` decimal(25,4) DEFAULT NULL,
  `quantity` decimal(15,4) NOT NULL,
  `warehouse_id` INTEGER DEFAULT NULL,
  `item_tax` decimal(25,4) DEFAULT NULL,
  `tax_rate_id` INTEGER DEFAULT NULL,
  `tax` TEXT  DEFAULT NULL,
  `item_tax_2` decimal(25,4) DEFAULT NULL,
  `tax_rate_2_id` INTEGER DEFAULT NULL,
  `tax_2` TEXT  DEFAULT NULL,
  `discount` TEXT  DEFAULT NULL,
  `item_discount` decimal(25,4) DEFAULT NULL,
  `subtotal` decimal(25,4) NOT NULL,
  `serial_no` TEXT  DEFAULT NULL,
  `real_unit_price` decimal(25,4) DEFAULT NULL,
  `product_unit_id` INTEGER DEFAULT NULL,
  `product_unit_code` TEXT  DEFAULT NULL,
  `unit_quantity` decimal(15,4) NOT NULL,
  `gst` TEXT  DEFAULT NULL,
  `cgst` decimal(25,4) DEFAULT NULL,
  `sgst` decimal(25,4) DEFAULT NULL,
  `igst` decimal(25,4) DEFAULT NULL,
  `price_before_tax` decimal(25,4) DEFAULT NULL
);

''';

const String PurchaseItemsSql = '''
CREATE TABLE `sma_purchase_items` (
`id` INTEGER NOT NULL PRIMARY KEY,
`purchase_id` INTEGER DEFAULT NULL,
`transfer_id` INTEGER DEFAULT NULL,
`product_id` INTEGER NOT NULL,
`product_code` TEXT  NOT NULL,
`product_name` TEXT  NOT NULL,
`option_id` INTEGER DEFAULT NULL,
`net_unit_cost` decimal(25,4) NOT NULL,
`quantity` decimal(15,4) NOT NULL,
`warehouse_id` INTEGER NOT NULL,
`item_tax` decimal(25,4) DEFAULT NULL,
`tax_rate_id` INTEGER DEFAULT NULL,
`tax` TEXT  DEFAULT NULL,
`item_tax_2` decimal(25,4) DEFAULT NULL,
`tax_rate_2_id` INTEGER DEFAULT NULL,
`tax_2` TEXT  DEFAULT NULL,
`discount` TEXT  DEFAULT NULL,
`item_discount` decimal(25,4) DEFAULT NULL,
`expiry` date DEFAULT NULL,
`subtotal` decimal(25,4) NOT NULL,
`quantity_balance` decimal(15,4) DEFAULT '0.0000',
`date` date NOT NULL,
`status` TEXT  NOT NULL,
`unit_cost` decimal(25,4) DEFAULT NULL,
`real_unit_cost` decimal(25,4) DEFAULT NULL,
`quantity_received` decimal(15,4) DEFAULT NULL,
`supplier_part_no` TEXT  DEFAULT NULL,
`purchase_item_id` INTEGER DEFAULT NULL,
`product_unit_id` INTEGER DEFAULT NULL,
`product_unit_code` TEXT  DEFAULT NULL,
`unit_quantity` decimal(15,4) NOT NULL,
`serial_no` TEXT  DEFAULT NULL,
`gst` TEXT  DEFAULT NULL,
`cgst` decimal(25,4) DEFAULT NULL,
`sgst` decimal(25,4) DEFAULT NULL,
`igst` decimal(25,4) DEFAULT NULL,
`product_unit_id_selected` INTEGER DEFAULT NULL,
`shipping_unit_cost` decimal(25,4) DEFAULT '0.0000',
`profitability_margin` decimal(5,2) DEFAULT '0.00',
`consumption_purchase` decimal(25,4) DEFAULT NULL,
`returned_quantity` decimal(15,4) DEFAULT '0.0000',
`registration_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
`expense_category_creditor_ledger_id` INTEGER DEFAULT NULL,
`calculated_avg_cost` decimal(25,4) DEFAULT NULL
);
''';

const String PurchasesSql = '''
CREATE TABLE `sma_purchases` (
`id` INTEGER NOT NULL PRIMARY KEY,
`id_cloud` INTEGER NOT NULL ,
`reference_no` TEXT  NOT NULL,
`date` datetime DEFAULT NULL,
`supplier_id` INTEGER NOT NULL,
`supplier` TEXT  NOT NULL,
`warehouse_id` INTEGER NOT NULL,
`note` TEXT  NOT NULL,
`total` decimal(25,4) DEFAULT NULL,
`product_discount` decimal(25,4) DEFAULT NULL,
`order_discount_id` TEXT  DEFAULT NULL,
`order_discount` decimal(25,4) DEFAULT NULL,
`total_discount` decimal(25,4) DEFAULT NULL,
`product_tax` decimal(25,4) DEFAULT NULL,
`order_tax_id` INTEGER DEFAULT NULL,
`order_tax` decimal(25,4) DEFAULT NULL,
`total_tax` decimal(25,4) DEFAULT '0.0000',
`shipping` decimal(25,4) DEFAULT '0.0000',
`grand_total` decimal(25,4) NOT NULL,
`paid` decimal(25,4) NOT NULL DEFAULT '0.0000',
`status` TEXT  DEFAULT '' ,
`payment_status` TEXT  DEFAULT 'pending',
`created_by` INTEGER DEFAULT NULL,
`updated_by` INTEGER DEFAULT NULL,
`updated_at` timestamp NULL DEFAULT NULL,
`attachment` TEXT  DEFAULT NULL,
`payment_term` INTEGER DEFAULT NULL,
`due_date` date DEFAULT NULL,
`return_id` INTEGER DEFAULT NULL,
`surcharge` decimal(25,4) NOT NULL DEFAULT '0.0000',
`return_purchase_ref` TEXT  DEFAULT NULL,
`purchase_id` INTEGER DEFAULT NULL,
`return_purchase_total` decimal(25,4) NOT NULL DEFAULT '0.0000',
`cgst` decimal(25,4) DEFAULT NULL,
`sgst` decimal(25,4) DEFAULT NULL,
`igst` decimal(25,4) DEFAULT NULL,
`closed_year` smallINTEGER DEFAULT '0' ,
`rete_fuente_percentage` decimal(6,3) DEFAULT '0.000',
`rete_fuente_total` decimal(25,4) DEFAULT '0.0000',
`rete_fuente_account` INTEGER DEFAULT '0',
`rete_fuente_base` decimal(25,4) DEFAULT NULL,
`rete_iva_percentage` decimal(6,3) DEFAULT '0.000',
`rete_iva_total` decimal(25,4) DEFAULT '0.0000',
`rete_iva_account` INTEGER DEFAULT '0',
`rete_iva_base` decimal(25,4) DEFAULT NULL,
`rete_ica_percentage` decimal(6,3) DEFAULT '0.000',
`rete_ica_total` decimal(25,4) DEFAULT '0.0000',
`rete_ica_account` INTEGER DEFAULT '0',
`rete_ica_base` decimal(25,4) DEFAULT NULL,
`rete_other_percentage` decimal(6,3) DEFAULT '0.000',
`rete_other_total` decimal(25,4) DEFAULT '0.0000',
`rete_other_account` INTEGER DEFAULT '0',
`rete_other_base` decimal(25,4) DEFAULT NULL,
`order_discount_method` INTEGER DEFAULT '2' ,
`purchase_currency` TEXT  DEFAULT NULL,
`purchase_currency_trm` decimal(25,4) DEFAULT NULL,
`purchase_type` INTEGER DEFAULT '1' ,
`credit_ledger_id` INTEGER DEFAULT NULL ,
`payment_affects_register` INTEGER DEFAULT '1' ,
`cost_center_id` INTEGER DEFAULT NULL,
`biller_id` INTEGER DEFAULT NULL,
`consecutive_supplier` TEXT  DEFAULT NULL,
`document_type_id` INTEGER DEFAULT NULL,
`rete_fuente_id` INTEGER DEFAULT NULL,
`rete_iva_id` INTEGER DEFAULT NULL,
`rete_ica_id` INTEGER DEFAULT NULL,
`rete_other_id` INTEGER DEFAULT NULL,
`purchase_origin` TEXT  DEFAULT NULL,
`purchase_origin_reference_no` TEXT  DEFAULT NULL,
`prorated_shipping_cost` decimal(25,4) DEFAULT '0.0000',
`consumption_purchase` decimal(25,4) DEFAULT NULL,
`resolucion` TEXT  DEFAULT NULL,
`due_payment_method_id` INTEGER DEFAULT NULL,
`registration_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
`expense_causation` INTEGER DEFAULT NULL ,
`return_other_concepts` tinyINTEGER NOT NULL DEFAULT '0' ,
`rete_fuente_assumed` INTEGER DEFAULT NULL,
`rete_iva_assumed` INTEGER DEFAULT NULL,
`rete_ica_assumed` INTEGER DEFAULT NULL,
`rete_other_assumed` INTEGER DEFAULT NULL,
`rete_fuente_assumed_account` INTEGER DEFAULT NULL,
`rete_iva_assumed_account` INTEGER DEFAULT NULL,
`rete_ica_assumed_account` INTEGER DEFAULT NULL,
`rete_other_assumed_account` INTEGER DEFAULT NULL,
`rete_bomberil_percentage` decimal(6,3) DEFAULT '0.000',
`rete_bomberil_total` decimal(25,4) DEFAULT '0.0000',
`rete_bomberil_account` INTEGER DEFAULT '0',
`rete_bomberil_base` decimal(25,4) DEFAULT NULL,
`rete_autoaviso_percentage` decimal(6,3) DEFAULT '0.000',
`rete_autoaviso_total` decimal(25,4) DEFAULT '0.0000',
`rete_autoaviso_account` INTEGER DEFAULT '0',
`rete_autoaviso_base` decimal(25,4) DEFAULT NULL,
`rete_bomberil_id` INTEGER DEFAULT NULL,
`rete_autoaviso_id` INTEGER DEFAULT NULL,
`rete_bomberil_assumed_account` INTEGER DEFAULT NULL,
`rete_autoaviso_assumed_account` INTEGER DEFAULT NULL
);
''';

List<String> indexCreation = [
  'CREATE UNIQUE INDEX sma_products_id ON sma_products (id_cloud);',
  'CREATE UNIQUE INDEX sma_sales_id ON sma_sales (id_cloud);',
  'CREATE UNIQUE INDEX sma_settings_id ON sma_settings (setting_id);',
  'CREATE UNIQUE INDEX sma_product_photos_id ON sma_product_photos (id_cloud);',
  'CREATE UNIQUE INDEX sma_product_variants_id ON sma_product_variants (id_cloud);',
  'CREATE UNIQUE INDEX sma_pos_settings_id ON sma_pos_settings (id);',
  'CREATE UNIQUE INDEX sma_payment_methods_id ON sma_payment_methods (id_cloud);',
  'CREATE UNIQUE INDEX sma_brands_id ON sma_brands (id_cloud);',
  'CREATE UNIQUE INDEX sma_warehouses_products_id ON sma_warehouses_products (id_cloud);',
  'CREATE UNIQUE INDEX sma_addresses_id ON sma_addresses (id_cloud);',
  'CREATE UNIQUE INDEX sma_customer_groups_id ON sma_customer_groups (id_cloud);',
  'CREATE UNIQUE INDEX sma_companies_id ON sma_companies (id_cloud);',
  'CREATE UNIQUE INDEX sma_product_prices_id ON sma_product_prices (id_cloud);',
  'CREATE UNIQUE INDEX sma_biller_data_id ON sma_biller_data (id_cloud);',
  'CREATE UNIQUE INDEX sma_price_groups_id ON sma_price_groups (id_cloud);',
  'CREATE UNIQUE INDEX sma_tax_rates_id ON sma_tax_rates (id_cloud);',
  'CREATE UNIQUE INDEX sma_documentypes_id ON sma_documentypes (id_cloud);',
  'CREATE UNIQUE INDEX sma_countries_id ON sma_countries (CODIGO);',
  'CREATE UNIQUE INDEX sma_states_id ON sma_states (CODDEPARTAMENTO);',
  'CREATE UNIQUE INDEX sma_cities_id ON sma_cities (CODIGO);',
  'CREATE UNIQUE INDEX sma_documents_types_id ON sma_documents_types (id_cloud);',
  'CREATE UNIQUE INDEX sma_categories_id ON sma_categories (id_cloud);',
  'CREATE UNIQUE INDEX sma_units_id ON sma_units (id_cloud);',
  'CREATE UNIQUE INDEX sma_unit_prices_id ON sma_unit_prices (id);',
  'CREATE UNIQUE INDEX sma_groups_id ON sma_groups (id_cloud);',
  'CREATE UNIQUE INDEX sma_warehouses_id ON sma_warehouses (id_cloud);',
  'CREATE UNIQUE INDEX sma_biller_documents_types_id ON sma_biller_documents_types (biller_id,document_type_id);',
  'CREATE UNIQUE INDEX sma_wishlist_id ON sma_wishlist (customer_id,product_id);',
  'CREATE UNIQUE INDEX sma_order_sales_id ON sma_order_sales (id_cloud);',
  'CREATE UNIQUE INDEX sma_quotes_id ON sma_quotes (id_cloud);',
  'CREATE UNIQUE INDEX sma_purchases_id ON sma_purchases (id_cloud);',
  'CREATE UNIQUE INDEX sma_order_sale_items_id ON sma_order_sales (id);',
  'CREATE UNIQUE INDEX sma_product_preferences_id ON sma_product_preferences (id_cloud);',
  'CREATE INDEX `sma_payment_sale_id` ON `sma_payments` (`sale_id`);',
  //index for sma_payments
  // to locally save order sale items
  // 'CREATE UNIQUE INDEX sma_order_sale_items_id ON sma_order_sale_items (product_id,sale_id,product_unit_id);',
];

List<String> syncIds = [
  "INSERT INTO sync (id) VALUES (1);",
  "INSERT INTO sync (id) VALUES (2);",
  "INSERT INTO sync (id) VALUES (3);",
  "INSERT INTO sync (id) VALUES (4);",
  "INSERT INTO sync (id) VALUES (5);",
  "INSERT INTO sync (id) VALUES (6);",
  "INSERT INTO sync (id) VALUES (7);",
  "INSERT INTO sync (id) VALUES (8);",
  "INSERT INTO sync (id) VALUES (9);",
  "INSERT INTO sync (id) VALUES (10);",
  "INSERT INTO sync (id) VALUES (11);",
  "INSERT INTO sync (id) VALUES (12);",
  "INSERT INTO sync (id) VALUES (13);",
  "INSERT INTO sync (id) VALUES (14);",
  "INSERT INTO sync (id) VALUES (15);",
  "INSERT INTO sync (id) VALUES (16);",
  "INSERT INTO sync (id) VALUES (17);",
  "INSERT INTO sync (id) VALUES (18);",
  "INSERT INTO sync (id) VALUES (19);",
  "INSERT INTO sync (id) VALUES (20);",
  "INSERT INTO sync (id) VALUES (21);",
  "INSERT INTO sync (id) VALUES (22);",
  "INSERT INTO sync (id) VALUES (23);",
  "INSERT INTO sync (id) VALUES (24);",
  "INSERT INTO sync (id) VALUES (25);",
  "INSERT INTO sync (id) VALUES (26);",
  "INSERT INTO sync (id) VALUES (27);",
];
